### ISSUE TITLE
Settings table cleanup

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#10318]
Our settings table needs a little bit of cleanup. The intended conventions got lost and broken, and chaos has ensued! 

To fix this, we've agreed on the following conventions:

**Key**

- must be snake_case
- should be descriptive and unique
- for keys that appear in APIs, they should be named as they will be in the API

**Value**

- can be one of: String, Number, Boolean or Array (a list of similar items)
- must not be a JSON Object
- must be nullable or have a sensible default

**Type**

- Explicitly used to declare what type the `value` contains
- String, Number, Boolean or Array (a list of similar items)
- Array could be extended to specify the type of item they will contain - e.g. `Array<String/Number/Boolean/StripePlan>`

**Group**

- Groups should be used to represent settings that are fetched and updated from the API together.
- The groups have special implied access rules:
    - `site` - available via the Admin and Content Settings APIs
    - `core` - not available via any API
    - anything else - available via the Admin Settings API
- New groups can be added as needed, if we need a new group with a new implied access rule, we can also do this.

**Flags**

- NULL - default
- PUBLIC - will appear in the unauthenticated Admin and Members Site APIs
- RO - cannot be written directly via the Admin API - is read only
- PUBLIC,RO - is both public and read only

----

## TODO

To bring our existing settings into line with these conventions we need to make the following changes

General cleanup:
- [x] Remove `force_i18n`, `permalinks` and `members_session_secret`
- [x] Rename `default_locale` to `lang` and `active_timezone` to `timezone`
- [x] Rename `ghost_head` and `ghost_foot` to `codeinjection_head` and `codeinjection_foot`
- [x] Rename `brand.publicationColor` to `accent_color`

New `group` and `special` concept:
- [x] Add a new column called `group`, give each setting a new correct group name (inc changing blog -> site)
- [x] Add group support to the API and update Ghost Admin to use group, not type
- [x] Add a special column to indicate extra API rules
- [x] Implement special rules at API level and in Ghost admin

Types and Validations:
- [x] Repurpose the old type column to contain the value type (String, Boolean, Array)
- [x] Ensure that default-settings.json has useful validations for as many settings as possible

Bigger reworks:
- [x] Rework members_subscription_settings to a set of key-values in a shared group
- [x] Rework stripe_connect_integration to a set of key-values in a shared group
- [x] Rework bulk_email_settings to a set of key-values in a shared group
- [x] Simplify `unsplash` to a boolean (https://github.com/TryGhost/Team/issues/331)
- [x] Change `slack` into two fields (https://github.com/TryGhost/Team/issues/331)
- [x] Rework labs into a group with individual key-value pairs (https://github.com/TryGhost/Team/issues/332)

Later:
- Improve validations further by exposing them over the API, either by coping them into a column or using JSON schema

**Comment by kevinansfield** [comment]
Not stale

**Comment by kevinansfield** [comment]
> slack and unsplash need moving to a new type, e.g. credentials

Does `credentials` make sense for Unsplash? There are no credentials stored for Unsplash, the only setting used is a toggle to enable/disable the Unsplash image selector in Ghost-Admin.
