### ISSUE TITLE
Decouple Theme Layer from Settings Cache

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#10381]
## Description

When we have worked on the Settings Content API v2, we discovered two things:

- the theme layer needs access to the public available settings fields, [see](https://github.com/TryGhost/Ghost/blob/2.11.0/core/server/services/themes/middleware.js#L49)
- the Content API needs to decide which attributes to return, [see](https://github.com/TryGhost/Ghost/blob/2.11.0/core/server/api/v2/settings-public.js#L11)

Both places use a new helper of the settings cache - .[getPublic](https://github.com/TryGhost/Ghost/blob/2.11.0/core/server/services/settings/cache.js#L99), which was invented to solve this requirement of serving public setting fields.

## Problem

The settings cache is a cache for the settings model. This gives us synchronous access in the code base. That is pretty cool and easy.

The theme layer was always coupled with the settings cache. The `.getPublic` function was a first good step to bundle the attributes in one place, but that did not solve coupling. If we think of future Ghost, the API and the theme layer are two different parts, which should not use any dependencies of each other. Furthermore, right now the settings cache has introduced another serialisation layer for the settings through the `.getPublic` function.

Further discoveries:

- a controller should always return a model result, not an API result ([see comment](https://github.com/TryGhost/Ghost/blob/2.11.0/core/server/api/v2/settings-public.js#L10)). The API output serializer should define which attributes to return or which attributes to rename
- the functional settings test should not be coupled to the settings cache, neither to the model schema ([see](https://github.com/TryGhost/Ghost/blob/2.11.0/core/test/functional/api/v2/content/settings_spec.js#L10))

## Solution

@ErisDS and me were talking about this problem and we think the theme layer should talk to the Content API - a request to the public settings endpoint.

The v0.1 API has no endpoint for settings. We probably need to work around this for now and wait till we drop it. **Probably needs further research if that would be okay.**

## Tasks

- [ ] theme layer uses Content Settings API
- [ ] Settings API Controller get's cached settings model from settings cache and API output serializer takes care of the rest
- [ ] decouple functional test and use test utility for API response expectations

To be continued/iterated.
