### ISSUE TITLE
Update moment-timezone dependency

### ISSUE THREAD

**Issue by naz** [TryGhost/Ghost#10870]
### Context 

After Renovate bumped moment-timezone to `0.5.25` from `0.5.23` one of the [regression tests](https://github.com/TryGhost/Ghost/blob/cf499c3/core/test/regression/importer/importer_spec.js#L142) started [failing](travis-ci.org/TryGhost/Ghost/jobs/553428813). The reason test failed, was a change in `format()` output for [this](https://github.com/TryGhost/Ghost/blob/cf499c3/core/test/regression/importer/importer_spec.js#L180) assertion. The format was using local timezone instead of globally set 'UTC' one. The version in which the behavior change was introduced in moment-timezone [0.5.24](https://github.com/moment/moment-timezone/releases/tag/0.5.24). Was unable to pin down/replicate the issue in a clean environment. Added [description](https://github.com/moment/moment-timezone/issues/749#issuecomment-508191550) of initial findings mentioned in the issue of `moment-timezone` repository.

### TODO

The version bump will be reverted for now and added to ignore list in Renovate until the original issue is better understood. For someone who picks this issue up should make sure:
- [ ] bump `moment-timezone` package version to the latest in core
- [ ] bump `moment-timezone` package version in SDK
(Revert https://github.com/TryGhost/Ghost-SDK/commit/5f0fc04fdba79028bf9d7007a03d1a319acdedc3)
- [ ] make sure [default UTC timezone](https://github.com/TryGhost/Ghost/blob/8aac74b/core/server/overrides.js#L25) works globally 
- [ ] remove `moment-timezone` from Renovate ignore list 

NOTE: When updating to a newer version please pay attention to performance changes as `moment` is known to be one of the main perf. bottlenecks in Ghost.

**Comment by chanceeakin** [comment]
Pulled down and attempted a version bump to `moment-timezone@0.5.26`. Issue still persists in core during regression tests. Leaving this breadcrumb to save the next person a few minutes.

```
 1) Integration: Importer
       Empty database (except of owner user), general tests
         cares about invalid dates and date formats:

      AssertionError: expected '2013-10-18T18:58:44-05:00' to equal '2013-10-18T23:58:44Z'
      + expected - actual

      -2013-10-18T18:58:44-05:00
      +2013-10-18T23:58:44Z

    at Assertion.fail (node_modules/should/cjs/should.js:275:17)
    at Assertion.value (node_modules/should/cjs/should.js:356:19)
    at core/test/regression/importer/importer_spec.js:180:83
    at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:15:14)
```

**Comment by AlphaWong** [comment]
I open a PR for it
https://github.com/TryGhost/Ghost/pull/11245

plz take a look is resolve it for not ?

**Comment by ErisDS** [comment]
We're going to switch to luxon instead, see https://github.com/TryGhost/Ghost/issues/13648
