### ISSUE TITLE
Setting for global @site SEO meta data (title/description)

### ISSUE THREAD

**Issue by gargol** [TryGhost/Ghost#10921]
### Problem

There is no way to set SEO metadata to the root site in the same way as to posts/pages.

### Context

All data (posts/pages/users/tags) in ghost has a concept of setting custom metadata for SEO - except for the main site’s settings/general, where you can set a “site title” and a “site description” - which are also used for metadata, but cannot be customised.

### Solution
The settings table will be expanded with additional entries with type:'blog' and keys similar to how `posts` table manages SEO data for it's `meta_title`/`meta_description` etc. fields. Specifically, these fields will be added:
- meta_title
- meta_description
- og_image
- og_title
- og_description
- twitter_image
- twitter_title
- twitter_description

The Admin UI "general settings" screen will be expanded with additional fields in the new "Site SEO" section. 

### TODO:
- [x] Changes in Admin API for @gargol
- [x] Make new fields available in  Content API's `GET /settings` endpoint @gargol
- [x] Adjust theme helpers to use new SEO fields @gargol (https://github.com/TryGhost/Ghost/pull/10930)
- [x] Admin-Client implementation of "Site SEO" section
- [ ] Document new fields for {{@site}} helper and Content API `/settings` endpoint
- [ ] Update gatsby-starter-ghost/11ty-starter-ghost to use new fields

**Comment by naz** [comment]
New global defaults for twitter/og were meant to be used as a fallback for individual posts/pages and were updated in https://github.com/TryGhost/Ghost/commit/f3e0949c730b1c59aff952b7cdcd297d40188678.
