### ISSUE TITLE
Image captions with unsupported HTML break the editor

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#11779]
# Issue Summary

If an image caption ends up with unsupported HTML (either via paste or via the API), opening that post in the editor throws an error which results in captions being un-editable and the PSM un-openable.

### To Reproduce

1. Create a test post with an image and a caption
2. Modify post's `mobiledoc` field in the database so the caption is wrapped in `<p>{previous caption}</p>`
3. Reload the post in the editor - the caption is now uneditable
4. Modify the post's `mobiledoc` field in the database again changing to `<p>Test</p> <small>Unsupported</small>`
5. Reload the post in the editor. The error below is displayed in the console, the caption isn't visible, and the PSM won't open

```
Uncaught TypeError: Cannot read property 'element' of undefined
    at Cursor._findNodeForPosition (cursor.js:97)
    at Cursor.selectRange (cursor.js:116)
    at Editor.selectRange (editor.js:428)
    at PostEditor._renderRange (post.js:74)
    at lifecycle-callbacks.js:34
    at Array.forEach (<anonymous>)
    at LifecycleCallbacks.runCallbacks (lifecycle-callbacks.js:33)
    at PostEditor.runCallbacks (post.js:103)
    at PostEditor.complete (post.js:1449)
    at Editor.run (editor.js:761)
```

### TODO:

- [ ] fix basic html cleaning function to properly remove unknown content
- [ ] fix paste if it's not cleaning content
- [ ] ensure caption content is cleaned when rendering caption inputs
  - [ ] in editor
  - [ ] in renderer

**Comment by kevinansfield** [comment]
I was able to reproduce this by selecting content from forbes.com that covers text and a photo with a caption. Example from https://www.forbes.com/sites/sergeiklebnikov/2020/04/28/stocks-rally-dow-rises-over-300-points-as-investors-become-more-optimistic-about-reopening-the-economy/:

<img width="1012" alt="Screenshot 2020-04-28 at 17 06 31" src="https://user-images.githubusercontent.com/415/80510445-a4a86d80-8972-11ea-95ad-cb22499bbce2.png">

That suggests the underlying problem is that our parsers are inserting unsupported HTML into the caption field of image cards.
