### ISSUE TITLE
[Members] Direct portal links to checkout plans

### ISSUE THREAD

**Issue by rishabhgrg** [TryGhost/Ghost#12365]
Currently this can only be done using `data-` attributes, which means the links only work from inside the publication and not from, for example, an email.

**MVP Solution**

- A new portal signup link for monthly plan
- A new portal signup link for yearly plan

**Improvements**

- A new portal signup link for "free" plan, which opens signup popup, with plans hidden
- Better error handling, open default portal for any unknown, or unhandled action.

### Tasks

- [x]  UI for MVP
- [x]  Portal handling for MVP
  - [x] browser back button from Stripe checkout takes users to infinite navigation loop
- [x]  UI for improvement link
  - [x] Clicking on any of these links we shouldn’t display the portal popup but navigate directly to Stripe checkout
- [x]  Portal handling for improvement link
  - [x] Link (signup/free) that opens the portal popup but hides all plans
- [x]  Error handling
- [x] Stripe back button takes users to home. should take them to whereever they came from

**Comment by rishabhgrg** [comment]
Finished with https://github.com/TryGhost/Portal/commit/7b76d7a47a90dd9100645bef749efe51fb37d46e
