### ISSUE TITLE
✨ Custom redirects for members after signup 

### ISSUE THREAD

**Issue by allouis** [TryGhost/Ghost#12366]
Site owners want to be able to show a custom message after a member has subscribed on their site.

Currently the only way to do this is by modifying the theme to redirect or show content based on the query parameters present after a magic link has been clicked. Our theme Lyra has [an example of this here](https://github.com/TryGhost/Lyra/blob/3d33452e421ec47e0fb050c25df671e6904a62f9/default.hbs#L98-L100).

Site owners that are less technical want to be able to customise this experience without having to modify the theme.

**MVP Solution**

- A new setting for storing paid subscription redirect path (default to "/")
- A new setting for storing free subscription redirect path (default to "/")
- After successful sign up or subscribe, redirect to the appropriate path based on the members subscription status

**Improvements**

- Support for external redirect URLs, rather than just paths
- Minimize flickered when redirecting externally

### Tasks

- [x]  New settings & migrations [Ghost PR #12370](https://github.com/TryGhost/Ghost/pull/12370)
- [x]  UI for new settings [Ghost-Admin PR #1768](https://github.com/TryGhost/Ghost-Admin/pull/1768)
- [x]  Middleware to redirect based on new settings [Ghost PR #12372](https://github.com/TryGhost/Ghost/pull/12372)
- [x] Allow the user to set an absolute (internal to the site) URL in the portal settings [Ghost-Admin PR #1775](https://github.com/TryGhost/Ghost-Admin/pull/1775)
- [x]  Disable portal notification when redirecting to a page other than the homepage [Ghost PR #12386](https://github.com/TryGhost/Ghost/pull/12386)
- [x] Support for redirecting to URL's outside of the site
  - [x] Update Middleware to handle redirecting to external absolute URL's [Ghost PR #12391](https://github.com/TryGhost/Ghost/pull/12391)
  - [x] Update UI to allow for storing external absolute URL's [Ghost-Admin PR #1778](https://github.com/TryGhost/Ghost-Admin/pull/1778)

**Comment by Maxszik** [comment]
"Site owners want to be able to show a custom message after a member has subscribed on their site."
Comment: a reminder that many newsletter providers provide the options to show a custom message/redirect page _both_ when it comes to the "Pls confirm by checking your mailbox" _and_ the "Congratulations you're a subscriber and all set up", two different steps in other words.

I think this would be useful.

**Comment by allouis** [comment]
Hey @Maxszik we don't accept feature requests via github, please use the forum instead! https://forum.ghost.org/c/Ideas/5

**Comment by allouis** [comment]
Done! :tada: 

All relevant code has been linked to in the body of this issue
