### ISSUE TITLE
✨ Members cancellation feedback

### ISSUE THREAD

**Issue by allouis** [TryGhost/Ghost#12403]
When members cancel their premium subscription, it's common for site owners to want to understand why they cancelled, and if there's anything they could've done better.

### Solution

- Add UI to Portal cancellation screen to enter cancellation reason
- Store cancellation reason as metadata on the Stripe Subscription
- Add cancellation reason columns to subscriptions table and replicate metadata there
- Display cancellation reason in subscription section in Ghost-Admin

### Tasks

- [x] Portal UI for Member to enter cancellation reason [Portal PR #111](https://github.com/TryGhost/Portal/pull/111)
- [x] Members API to handle new cancellation reason parameter [Ghost PR #12406](https://github.com/TryGhost/Ghost/pull/12406)
  - [x] Set metadata on Stripe Subscription [Members PR #221](https://github.com/TryGhost/Members/pull/221)
  - [x] Store cancellation reason in subscriptions table [Members PR #222](https://github.com/TryGhost/Members/pull/222)
- [x] Schema & Migrations for new column to subscriptions table [Ghost PR #12405](https://github.com/TryGhost/Ghost/pull/12405)
- [x] Update models to include new cancellation_reason column in serialization [Ghost PR #12411](https://github.com/TryGhost/Ghost/pull/12411)
- [x] Ghost-Admin UI to show cancellation reason on subscriptions due to cancel [Ghost-Admin PR #1782](https://github.com/TryGhost/Ghost-Admin/pull/1782)

**Comment by rishabhgrg** [comment]
Everything for this feature is now in master across Repos 🎉
