### ISSUE TITLE
Recurring and scheduled jobs support

### ISSUE THREAD

**Issue by matthanley** [TryGhost/Ghost#12427]
## Problem
In order to implement email analytics Ghost needs a robust system for running recurring, scheduled jobs as background processes.

### Expected Outcomes
We need to be able to define jobs which:

- **Run in the background:** process the job in the background outside the main request flow. The ability to offload to another process/thread would be ideal (and Node.js has worker threads from v12)
- **Shutdown gracefully:** terminate any running background job gracefully on shutdown - meaning we do our best to allow a started job to finish, and can restart recurring jobs on boot.
- **Have a low overhead:** run regularly scheduled jobs like polling for email events, without huge overhead where this functionality is not needed.

### Technical solution considerations
**Jobs** run to collect and process analytical data **are [idempotent](https://en.wikipedia.org/wiki/Idempotence)** and only need to be started on specified schedule (interval). Because of this simplification, there is no need for retry, restart or provide any additional interface from job scheduler.

Analytics jobs are going to self manage their schedule definition to run on an interval at which they would be able to finish execution. This should make sure there's **no job overlapping.** In other words, it's up to the client to schedule jobs with enough interval, so they don't run at the same time causing possible conflicts.

Schedule expression **format** needs to define simple recurring schedule e.g.: run every 5 minutes. Because of this simplicity and common pattern in most established schedulers, will rely on [crontab](https://www.gnu.org/software/mcron/manual/html_node/Crontab-file.html) as main format. [Human readable expressions](https://breejs.github.io/later/parsers.html#text) with possibility to expand that to use [rrule](https://icalendar.org/iCalendar-RFC-5545/3-8-5-3-recurrence-rule.html) might also be supported.

### To-dos:
- [x] allow scheduling jobs using existing (same process/event loop) job management mechanism (https://github.com/TryGhost/Ghost-Utils/commit/284e6217c78541173b21791a51d63459a7c44952)
- [x] offload job processing to worker threads (https://github.com/TryGhost/Ghost-Utils/commit/03f4add1bedc23f2773bbec207a22684d291f1b9)
- [x] document how to use job manager and how to write jobs (with best practices) (https://github.com/TryGhost/Ghost-Utils/commit/1078e628413402d43d79f1401e955aaf4dd5f0fa)
- [x] add a way to register one-off scheduled jobs to allow jobs like post scheduling (https://github.com/TryGhost/Ghost-Utils/issues/115)
- [x] add support for custom error handling (https://github.com/TryGhost/Ghost-Utils/issues/118)
- [x] scheduled job cancelation (https://github.com/TryGhost/Ghost-Utils/issues/119)
- [x] add support for immidiately executed offloaded jobs (https://github.com/TryGhost/Ghost-Utils/issues/117)

**Comment by naz** [comment]
All objectives of this issue have landed in @TryGhost/Ghost master.
