### ISSUE TITLE
Fix execution order of settings populateDefaults

### ISSUE THREAD

**Issue by naz** [TryGhost/Ghost#12568]
refs https://github.com/TryGhost/Team/issues/221

## Context
[populateDefaults](https://github.com/TryGhost/Ghost/blob/cbfdf79661fb06ea10f687f7c1409d43d002d67d/core/server/data/migrations/hooks/migrate/before.js#L8) call in Ghost's pre-boot phase causes `settings` table population before migrations have a chance to set correct values first (longer explanation available [here](https://github.com/TryGhost/Ghost/issues/12026#issuecomment-656140060)). The method is called in pre-boot only to allow "frontend" to initialize in a minimal way to serve _styled_ 503 page.

### Solution
The problem of the "frontend" boot before the "server" has a chance to initialize will be solved by flipping the dependence of the "server" on the "frontend". "server" will serve it's own 503 page until the boot is complete ("db.ready" event?) and then will notify the "frontend" to start it's initialization. 

### Todos
- [x] introduce independent 503 page served directly from Ghost server
- [x] initialize "frontend" after migrations and populateDefaults have finished execution 
- [x] change boot sequence to call [populateDefaults](https://github.com/TryGhost/Ghost/blob/cbfdf79661fb06ea10f687f7c1409d43d002d67d/core/server/data/migrations/hooks/migrate/before.js#L8) after migrations (https://github.com/TryGhost/Ghost/pull/12595)
- [x] design review of maintenance page
- [x] ~allow to add site icon to maintenance page (reference: https://github.com/TryGhost/Core/commit/fb0d0f09ba58703ee54683140acd07acea470316)~ the plan has been scrapped because of too much effort needed to reach the effect
  - [x] clean up the maintenance page

**Comment by naz** [comment]
Related to the issue is Ghost's boot sequence rewrite - https://github.com/TryGhost/Ghost/compare/main...ErisDS:boot-spike.

**Comment by naz** [comment]
An updated boot sequence has [landed in main](https://github.com/TryGhost/Ghost/commit/0b79abf5b252ab561a6024368d663eeff8da8727) and this initializes the settings defaults after the migrations are done.
