### ISSUE TITLE
💾 Member Events 

### ISSUE THREAD

**Issue by allouis** [TryGhost/Ghost#12602]
We want to store historical events related to members so that we can visualise this data in the admin. This issue focuses on the data side of things!

#### Tasks

- [x] Newsletter subscription status changes
  - [x] DB Table
  - [x] Model
  - [x] Event capturing
  - [x] Aggregate query
- [x] Paid subscription changes
  - [x] DB Table
  - [x] Model
  - [x] Event capturing
  - [x] Aggregate query
- [x] Status changes
  - [x] DB Table
  - [x] Model
  - [x] Addition of the 'comped' status 
  - [x] Event capturing
  - [x] Aggregate query
- [x] Email address changes
  - [x] DB Table
  - [x] Model
  - [x] Event capturing
- [x] Logins
  - [x] DB Table
  - [x] Model
  - [x] Event capturing
- [x] Payments
  - [x] DB Table
  - [x] Model
  - [x] Aggregate query
- [x] Event Repository 
  - [x] Member timeline
  - [x] Global timeline
  - [x] Subscriptions over time
  - [x] Gross volume over time
  - [x] MRR over time

**Comment by allouis** [comment]
This has been completed in all of the above linked PR's
