### ISSUE TITLE
Member Event APIs

### ISSUE THREAD

**Issue by rishabhgrg** [TryGhost/Ghost#12633]
refs https://github.com/TryGhost/Ghost/issues/12602

This issue tracks APIs on top of member events that allows us to visualize data in Admin Dashboard, using data collected in [this](https://github.com/TryGhost/Ghost/issues/12602) issue 

#### Tasks/Endpoints

- [x] Aggregate newsletter subscribers over time
- [x] Member events timeline
  - [x] Member email address change events
  - [x] Member subscription events
  - [x] Member login events
  - [x] Member payment events
- [x] Aggregate MRR over time
- [x] Top members (top 10 members sorted by open rate)
- [x] Activity feed of members
- [x] Newsletter open rates over time
- [x] Members
  - [x] Total
  - [x] Paid

**Comment by rishabhgrg** [comment]
Closed with https://github.com/TryGhost/Ghost/commit/0620ff6ae0af7bc01b3d7eb5decb778657d68d19 as all endpoints are now in `main`
