### ISSUE TITLE
Keyboard Shortcut Overhaul

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#1463]
There were a number of open issues on the [roadmap](https://github.com/TryGhost/Ghost/wiki/Roadmap) to do with shortcuts. They were:

* Display keyboard shortcut appropriate to OS #348
* Action Shortcut Keys #883
* Usability: Add support for keyboard-based navigation of content screen #1257
* [BUG] Select Word Keyboard Shortcut doesn't work #1275
* [BUG] markdown help popup is truncated on small screens #1273 
* [BUG] Shortcut.js assumes qwerty keyboard #1148
* [BUG] Editor: Link shortcut is the same as Lock Screen on Chromebooks #2444 / Consider changing the keyboard shortcut to "Ctrl + K" for "create link" #2865

Rather than treating each thing individually, we want to overhaul Ghost's keyboard shortcuts to provide a solution that will hopefully deal with most of them all in one go. 

The intention is to end up with a toolkit that we can use to provide:

- markdown shortcuts in the editor itself
- editor shortcuts for saving, publishing etc
- navigation shortcuts for moving around the entire Ghost application

Firstly the toolkit needs to provide tools for defining shortcuts. The existing tool for this, shortcuts.js is a bit limited, and is not in GitHub so potentially doesn't have the right license and cannot be added to. 

There are two main libraries on GitHub: https://github.com/ccampbell/mousetrap and https://github.com/madrobby/keymaster. They are both a little bit inactive (2 months), mousetrap provides sequences, keymaster provides scopes. Both are useful features, but I think mousetrap is the better option because sequences are super useful and I'm sure we can wrap the concept of scopes around it. If anyone thinks otherwise do let me know!

The toolkit should also provide for displaying these shortcuts when the `?` key is pressed as per #883 in such a way that the correct shortcut is presented for the current platform as per #348 (this means both displaying the correct shortcut for the platform and using the char ⌘ instead of Cmd). 

#1273 is an issue with the modals in Ghost, we need to investigate whether we can fix this, or whether it would be better to use http://www.impressivewebs.com/questionmark-js-shortcut-keys-displayed/ as suggested in #883.

Finally, we need to redesign the shortcuts themselves such that they do not clash with functions or secondary/tertiary characters on the various platforms and layouts.

The worst ones for clashing are the headings. The suggested solution is to use `ctrl` + `h` to output a 2nd level heading by default, and then use the number after in sequence to change it to another heading so `ctrl` + `h`, `3` would make a 3rd level heading.

So there are 3 main parts to this:

- [x] replace shortcuts.js with mousetrap (or keymaster if we change our minds)
- [x] introduce a better way of defining shortcuts, so that we can have different shortcuts for different things (markdown, editor, content screen, etc)
- [ ] improve the UI for displaying shortcuts
- [x] switch over markdown shortcuts to ones which do not clash cross-platform and layout

I'd like to see this done in a way such that it is kept away from the existing code as much as possible - it should be a module or a plugin.

**Comment by ErisDS** [comment]
The thing that is left here, is having a window that opens when you're not focused in the editor, with all the other keyboard shortcuts, exactly as GitHub does and is shown in the [comment above](https://github.com/TryGhost/Ghost/issues/1463#issuecomment-52266417) and was originally proposed in #883.

I think it would be a good idea to do this, especially as we now have so many keyboard shortcuts, they will only grow and there's not really a way to find out about them at the moment other than trial & error or reading the [support article](http://support.ghost.org/shortcuts/).

We have a couple of different sets of shortcuts:

- markdown shortcuts in the editor which are shown in part on the markdown model like `Ctrl/⌘ + B`
- other general editor screen shortcuts like `Alt + Shift + Z` for zen writing 
- content screen shortcuts like `o or Enter` to open a post for editing
- general shortcuts like `cmd + S` which work everywhere (ok this is the only one, but the Up/Down/Enter thing should probably work elsewhere).

Perhaps we should have a new modal to display them which opens with `?` everywhere except the editor where it has the button, and show the set which is most relevant at the top depending on where it is opened? So markdown at the top on the editor, content at the top on the content screen.

Not sure if the lack of consistency would make it confusing just thinking out loud really.

**Comment by ErisDS** [comment]
Going to close this for now, we can add a keyboard shortcut menu in future, should it become more useful or gain traction due to increasing numbers of shortcuts.
