### ISSUE TITLE
i18n Milestone 2: Framework and build tools

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#15502]
_This issue represents a single milestone within our i18n project. The full project is documented [on the Ghost forum](https://forum.ghost.org/t/hacktoberfest-project-i18n-for-portal-member-emails-comments-ui-sodosearch/33062)._

--- 

**Expected structure**

- A new `ghost/locales` folder in the monorepo contains namespaced JSON files e.g. `locales/es/common.json`, `/ocales/es/portal.json`, `locales/es/email.json`
- For Node.js/email-templates we do one of:
   - (Preferred) The correct path is loaded from config based on environment
   - ghost/locales gets copied into ghost/core somehow
- Then for react:
   - Use code-splitting to generate individual versions of portal for each supported locale.

**Goals:**

- [x] Get the basic pieces of i18next in place & configured according to [the tech spec](https://forum.ghost.org/t/hacktoberfest-project-i18n-for-portal-member-emails-comments-ui-sodosearch/33062#technical-plan-3)
- [x] Implement the expected structure (see above)
- [x] Figure out if we need to switch to vitejs in Portal to achieve the desired build (may need help from Ghost team)
- [x] Have 1 interpolated string in each of email and Portal
- [x] Tooling for extracting strings & generating files

-----

## Tasks:

- [x] Move Portal into the monorepo (Ghost team to complete soon)
- [x] Demo/spike of the build tool for Portal - I think this is the hardest part so we should do it first
- [x] Demo/spike of how locale files get pulled into Node.js for email templates
- [x] Demo/spike of i18next wiring so that there's one interpolated string in Portal and one in an email template
- [x] Demo/spike of a tooling that can grab the 2 interpolated strings e.g. `yarn translate es` would create `/locales/es/portal.js` and `/locales/es/email.js` each containing one string.

I'm hoping to find people interested in the different parts to do initial spike implementations - then we can figure out the tasks more clearly. 

---

**Notes on participating & Hacktoberfest:**

We aren't going to merge half-baked spikes or wiring that doesn't match the spec yet - so if you're just trying to get through Hacktoberfest as fast as possible, this is not the issue for you! (There are plenty of small bugs though!)

However, if you're using Hacktoberfest as a vehicle to find a cool & meaningful project to work on, this should be well up your street :)

We'll do our best to ensure that those who actively contribute value to this project get something merged and appropriately labelled by the end of Hacktoberfest 🎃

👉 If you're interested, drop a note to say Hi and which part you're interested in before getting stuck in, just in case we end up with multiple people trying to get the same things merged.

**Comment by ErisDS** [comment]
Portal is now officially part of the monorepo and the dev workflow is working really well.

By default `yarn dev` will pull the latest release of portal from jsDelivr. If you're actively working on Portal, you can run `yarn dev --portal` and you'll get your live local version of portal as well as Ghost & Ghost Admin 🙌 

Would love to get some volunteers to start wiring up i18next.

**Comment by daniellockyer** [comment]
Hi all! 👋🏻 The tasks above has been completed and milestone 2 is complete 🙂 We're doing some testing internally and then we'll look at opening it up to translations 🕺🏻
