### ISSUE TITLE
[Feature] Permalink Settings UI

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#1631]
The current Permalink Settings UI is just a checkbox to switch between WP style and Ghost style permalinks. But Ghost is capable of supporting many, many more formats. In order to make these formats accessible, we are going to add a new UI to the general settings pane that is going to look something like this:

![](https://cloud.githubusercontent.com/assets/120485/2731445/bef43b3e-c62c-11e3-979f-9afc39bfd3ff.png)

In order to ship this, the following tasks need to be completed:

* [x] Code up the UI in HTML & CSS ~~#3920~~ [Mockup here](https://github.com/TryGhost/Ghost/blob/master/core/client/html/permalinks.html)
* [x] Mockup needs fixing / would be good to have a gif showing how it is supposed to work ~~#4454~~
* [ ] Wire up the new UI as an ember component which replaces the existing checkbox (issue #4484)
* [ ] Implement validation on the client and server to ensure that only valid permalinks can be created with the UI and saved in the DB (issue #4486)
* [ ] Ensure the frontend correctly handles various permalinks https://github.com/TryGhost/Ghost/issues/4322, which depended on ~~https://github.com/TryGhost/Ghost/issues/4445~~

## Ghost Permalink Spec

The details of what permalink formats we support were originally covered by https://github.com/TryGhost/Ghost/issues/2057 and extended by https://github.com/TryGhost/Ghost/issues/3858

The full details of what constitutes a valid permalink as a result of those two issues are:

A permalink can contain any of the following items:

* `:slug`
* `:id` 
* `:year`
* `:month`
* `:day`
* `:author`
* santised custom text containing a-z, 0-9, - or _

To be a valid permalink:
* each item must be separated by a '/', 
* there should be a maximum of 5 items 
* one of them must be `:slug` or `:id` so that the post can be identified.
* no url part can be `ghost`

### Examples

I could set my blog posts to have a URL like any of these:

* `/:year/:month/:slug/`
* `/:year/:slug/`
* `/blogpost/:id/`
* `/post/:year/:month/:day/:slug/`
* `/:author/:slug/`
* And many more combinations

Please note that contrary to what is shown in the new UI, Ghost does not yet support having a tag in your permalink, because at present we have no way to indicate which tag would be the canonical one.

**Comment by ErisDS** [comment]
Short term, custom permalinks are working well if you configure them via the database. Long term we'll revisit adding the UI to settings again, or via some other method when it becomes more of a priority issue.

**Comment by jloh** [comment]
I asked [this question on slack](https://ghost.slack.com/archives/dev/p1479802938002029) however didn't get a response so thought I'd shoot a question on here. Is there any plans of implementing this for 1.0/x or a general overhaul of the whole permalink structure so you can do things like [sub pages](http://ideas.ghost.org/forums/285309-wishlist/suggestions/9774729-subpages) or put all posts under `/post` for example?

**Comment by ErisDS** [comment]
@jloh sorry for the slow reply. This issue represents the idea of adding a UI for the existing permalink settings. Adding this would not result in the ability to sub pages. It is already possible to put all posts under `/post`, however it can only be done by modifying the database rather than via a UI at present.

**Comment by Cellane** [comment]
@ErisDS Apologies for asking a partially unrelated question in the issue but I think this thread is the most related discussion to an issue I have right now. I’m thinking of migrating my site from Jekyll to Ghost and putting all posts under `/post` is exactly what I need – you mentioned in your comment that it can be done by modifying the database, although I wasn’t able to find any resource on that topic (other than this issue). Would you mind sharing more about how that would be done?

**Comment by kirrg001** [comment]
@Cellane There is a table called `settings`. 

> update settings set value='/post/:slug/' where \`key\`='permalinks';

This query makes it possible to change the location of all posts.

But **note**: We are about to ship the beta of [dynamic routing](https://github.com/TryGhost/Ghost/issues/9601). This feature makes it possible to configure your routes in a [yaml routing file](https://github.com/TryGhost/Ghost/issues/9528). I would recommend waiting for the upcoming release next week.

**Comment by Cellane** [comment]
@kirrg001 I see, thank you very much for this information! With that new piece of information in mind, I think I’ll spend the weekend doing the actual article migration (while avoiding modifying the `settings` table) and delay deploying the finished site for a few days until the beta version you mentioned is released. Thank you once again!
