### ISSUE TITLE
[Epic] Ghost and RSS

### ISSUE THREAD

**Issue by halfdan** [TryGhost/Ghost#3993]
## Description

Ghost currently uses the `rss` module to generate its RSS feed. There are a number of open issues with the module and it is not extensible (e.g. by apps). In addition to an audit of the feed structure (#2263) the RSS feed will need to be extensible and properly support caching (via ETags, #2777). 

## Steps

- [x] Develop new RSS module called [feed.js](https://github.com/halfdan/feed.js) that will replace `rss`. @halfdan
- [x] Make sure `feed.js` is at least on par with Ghost's current RSS feed. @halfdan
- [x] Audit feed structure and decide on necessary changes. #2263
- [ ] Allow extending the RSS feed via apps. #2365

**Comment by ErisDS** [comment]
Going to close this as node-rss caught up and is now fully extensible. The ETAG issue is also fixed I believe. This means the only thing left to do is #2365.
