### ISSUE TITLE
[Feature] Tag Management

### ISSUE THREAD

**Issue by novaugust** [TryGhost/Ghost#4248]
Here's the original UI issue: #3926 , and the markup was added in #4171. The big picture vision for tags is written up in the [Tag 101](https://github.com/TryGhost/Ghost/wiki/Tags-101) document on the wiki, which covers tonnes of advanced features.

---

In order to ship tag management we need to deliver a minimum working version. Here's what we think it should look like: 

![screenshot of simple tag list](http://puu.sh/cZyOy.png)

This list shows each tag in a list. The list needs to have infinite scroll applied to it, much the same as the users or posts list. The number on the right is the number of posts that the tag is associated with.

Clicking on any one of the tags in the list will open up the 'tag settings menu' or TSM :)

![screenshot of edit screen](http://puu.sh/cZAA0.png)

This allows for editing the tag name, slug, description, and post cover image. There is also a meta data screen the same as in the post settings menu. Editing the slug updates a live URL preview.

This screen should only appear for users with the role 'Editor' or higher.

Development How-To
===================
The tags UI is hidden behind a feature flag! To see, use, and develop with the tags settings you must set `tagsUI: true` in the `development` object of your `config.js`. 

E.g:

```
development: {
    url: 'http://localhost:2368',
    tagsUI: true,
    ...
```

Server Side
---------------------------------

### Tag API
- [x] Full BREAD baby! (Currently, only Browse is implemented) #4263
- [x] Output number of posts associated with tag (issue #4521)
- [x] Ensure API permissions are correct 

Client Side
-------------------------------

- [x] Add new page to settings #4260
- [x] BREAD (WIP PR #4489)
- [x] Add infinite scroll (done in PR #4489)
- [x] Add autosave and remove save button (issue #4517)
- [x] Add the cover image (issue #4506)
- [x] Add number of posts (issue #4683, requires #4521)
- [x] Permissions - Only editors and up
- [x] Add meta data screen (issue #4509)
- [x] Fixup the delete flow (issue #4633)
- [x] Dynamic URL preview (issue #4499)
- [ ] Dry up the code (issue #4642)

Themes
-------------

- [ ] Use tag meta data on tag archive pages (issue #4677)
- [x] Make sure `{{image}}` helper works for tags (issue #4506)

Bugs & Improvements
--------------------

- [x] Bug: Settings menu doesn't close on transition  bug ember (issue #4504)
- [x] UX Issue: Tag management list needs larger click area  ember (issue #4505)
- [ ] Tag Management: Functional Tests (issue #4507)
- [ ] Enforcing uniqueness of tag names (issue #4687)

See [Tag 101](https://github.com/TryGhost/Ghost/wiki/Tags-101) for a description of advanced features we'll be adding later like hierarchy, visibility and search.

**Comment by lemur3** [comment]
Howdy, unsure if this is the place to report it, knowing it is still being worked on.. but I've not been able to find it reported elsewhere..

I use ghost with the "fileStorage: false" option in my config due to the use of ephemeral storage and I noticed when using the tag management panel the section where an image is added has some odd behavior.

Initially there are multiple submit boxes and buttons for what presumably should simply be one box for the URL and a submit button.. But, even more interesting is if one clicks away out of this tag-info section and moves to another tag, and then another tag after that.. the URL boxes and submit buttons keep building up.

If one clicks away to another section, such as 'General' or 'Users' and returns to the 'tags' section to again click on a tag to edit its tag-info section, it returns to the initial errant amount of URL boxes and submit buttons.

this is happening on 0.5.7 with a postgres database and filestorage disabled.
 
here are some images showing first the initial state, and second what happens after navigating to a few other tags:

![tags1](https://cloud.githubusercontent.com/assets/7681885/5607199/cc848180-941e-11e4-88fb-7aff1affa65e.png)

![tags3](https://cloud.githubusercontent.com/assets/7681885/5607201/e2ea4af4-941e-11e4-8079-745de630f9e1.png)

**Comment by ErisDS** [comment]
@lemur3 That's really odd but I can reproduce it. Could you possibly raise it as a [bug](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md#bugs)? That way it's easier to track, thanks :+1:

**Comment by MaluNoPeleke** [comment]
Could you please also add this kind of tag list to the editor so that it is easier to use existing tags for new posts?

**Comment by ErisDS** [comment]
@MaluNoPeleke there is already a tag suggestions box in the editor - if you start typing it will pop up:

![](http://puu.sh/etFA1.png)

**Comment by MaluNoPeleke** [comment]
I know but if I don't remember which tags I have used for a similar post I have to search them by entering different letters which is not very user friendly.
Wordpress for example offers a list of the most used tags in a word cloud.

**Comment by ErisDS** [comment]
Now that 0.5.8 is released, we've achieved the basic tag management feature laid out in this issue. Therefore I'm closing this in favour of #4798.
