### ISSUE TITLE
Database Migration Improvements

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#4479]
This issue is a placeholder epic, and is in the process of being updated to include full details of all the changes and improvements we need to make to our database migration systems in order to make the process simpler.

One of the things that makes migrations really hard is the need to update the importer:

## Make migrations easier to do:
- [x] remove versioning from the importer
- [x] implement permissions migrations (issue #3910)
- [ ] add the missing column modifications to knex (issue #6471)

## Make migrations safer:
- [x] make it impossible to change the schema without doing a version increment (pr #4688)
- [x] make it impossible to change the permissions without doing a version increment (pr #4688)

**Comment by ErisDS** [comment]
Closing this issue, as the last remaining task is covered by #6471 and we don't need two issues to track one thing :grin:
