### ISSUE TITLE
Ghost Importer: Image Import and other Improvements

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#4605]
The Ghost importer has languished for a while, only able to import data if it's in Ghost's [JSON format](https://github.com/TryGhost/Ghost/wiki/import-format). This works really well for backing up, and moving Ghost blogs around. Official and unofficial tools have popped up to help convert other blog formats to Ghost's for WP, Tumblr and other platforms.

One thing Ghost's import/export format is lacking, is the ability to import images. This feature has never been high priority because anyone self-hosting can copy images into place, and anyone on Ghost(Pro) can email support to have their images imported. This is workable, but it's not ideal, not least because it means anyone importing images from another platform has to manually ensure their image paths are updated before importing.

With the need to migrate Roon users to Ghost easily, this feature has had a major bump in priority. At the same time as making import accept images, we also want to improve the general importer code to reduce complexity and provide more feedback. Finally, we want to open up the Ghost importer to handle a different format - importing from .md files. The .md file import may get moved to an app when the app platform launches, but for the time being this will help many many Roon and other platform users move to Ghost.

Tasks:

Image import
- [x] Accept and handle zip files (issue #4607)
- [x] Find and copy any image files (issue #4608)
- [x] Handle updating image paths in the data (issue #4609)

Other tasks
- [x] Remove versioning from importer (like the exporter)  (PR #4673)
- [ ] Provide better feedback on imports (issue TBR)
- [x] Support importing posts from .md files (issue #4691)

All the sub issues will be raised shortly

**Comment by ErisDS** [comment]
Closing in favour of #5422
