### ISSUE TITLE
[Feature] Advanced Tag Management

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#4798]
As of 0.5.8, we've shipped the basic [tag management feature](https://github.com/TryGhost/Ghost/issues/4248). There are a number of cleanup and improvement tasks that we still need to track, and the big picture vision for tags described in the [Tag 101](https://github.com/TryGhost/Ghost/wiki/Tags-101) document on the wiki, covers a number of advanced features that we can now add one at a time.

Remaining tasks from #4248:
- [x] Dry up the code (issue #4642)
- [x] Use tag meta data on tag archive pages (issue #4677)
- [x] Tag Management: Functional Tests (issue #4507)
- [x] Enforcing uniqueness of tag names (issue #4687)

Advanced features include (issues to be raised as and when we're ready to implement):
- [x] The query helper (https://github.com/TryGhost/Ghost/issues/4439)
- [x] Ordering (specific to a post, alphabetical, and by number of posts)
- [x] ~~Visibility / Private~~ Internal tags
- [ ] Primary tags (like a category)
- [ ] Hierarchy
- [x] Improved tag UI in the editor (#3800)
- [ ] Search and filtering

At present the [Tag 101](https://github.com/TryGhost/Ghost/wiki/Tags-101) document is the best resource for details on the advanced features.

**Comment by erisu** [comment]
Is the `Visibility / Private tags` feature similar to the `Private Blogging Password` feature, but in this case applied at a tag level?

**Comment by ErisDS** [comment]
@erisu wow, this is a pretty unloved issue, I just updated it a little 😁  

Internal tags have been available as a labs feature since 0.9.0. They create tags which are not output on the frontend, there is no password involved. The documentation is here: https://help.ghost.org/hc/en-us/articles/224169868-Internal-Tags-Beta.

**Comment by ErisDS** [comment]
We did the majority of this, the remaining potential features are:

- [ ] primary tag concept e.g. the first tag on an issue can be treated like a category and can appear in the URL
- [ ] tag hierarchy, e.g. a tag can have sub tags
- [ ] search and filtering, which is more of a case of having a UI and perhaps some upgrades to GQL.

I'm going to close this issue for now with the `later` tag, but I think it's more likely we will open new issues for any individual feature we choose to prioritise.
