### ISSUE TITLE
[Feature] User Welcome Tour

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5168]
The user welcome tour is a new feature intended to help guide users around the admin interface the first time they login to Ghost.  

![](http://puu.sh/hmaUn.gif)

The tour will feature a set of tips which are displayed in certain areas of the UI. It is more advanced than a simple series of steps, as some tips cannot be shown until a part of the UI is activated (i.e. after a user enters the editor). Each tour item consists of a throbbing icon which is triggered at a certain point. When the icon is  interacted with, it reveals a tip in a popover component. Each tip provides the option to close the tip, or opt out of all tips.

Building the  tour involves mostly client side work in ember, but also a small update to the user data model on the server side to store information about what has been seen or skipped. This issue has been broken down into several small issues in the hope it will encourage new contributors to have a go!

---

In detail:

On the server side, the user model should get a single additional field which stores a JSON object containing each tour item and whether or not it is seen. This data will be passed via the User API as per usual, such that Ember always knows the state of the currently logged in user's tour. This is covered in more detail in issue #5171.

On the client side, we need a way to define tour items including an identifier which matches data on the server side, the position of the throbbing icon and the content to be shown. Once defined that information needs to be wired up such that the throbbing icons are shown in the place, and that they correctly show the tip content. This is covered in more detail in issue #5169.

Further to getting the positioning and interactions working for the icon and tip, we also need to wire up the triggers that will cause the icons to show at the right time. These triggers may be based on user interactions, time delays, or a combination of both. I think this makes sense as a separate task #5170, but may need to be done in tandem with #5169.

When a tip, or the whole tour is dismissed in the client, we need to persist this data to the server by updating the users tour settings. Note that if the user skips the full tour, this should mark all items as 'seen'. This way we can still add new tour items later when additions are made. This is covered in more detail in issue #5172.

There is a decision to be made about whether existing Ghost users are shown the tour, or whether we should default the items to 'seen' for existing users. This is covered in more detail in issue #5173.

Last but not least the placement, content and trigger for each real tour item will need finalising in place by John, likely with some collaboration on wiring up new & fancier triggers. This doesn't need a separate issue :grin:

Note: none of this should appear on mobile.

Tasks:
- [x] Mock up HTML and CSS for the throbber and tip components #5084
- [ ] Wire up tour system to display #5169 
- [ ] Add triggers to tour system #5170 
- [x] Update the user model to store tour information #5171 
- [ ] Persist the closing and skipping of tips in the client #5172 
- [x] Migration rules for tour items #5173
- [ ] Finalise the placement, content and trigger for each tour item

**Comment by JohnONolan** [comment]
ALRIGHT! Got some slightly updated styles, and some content:

These are some cursory items, but I imagine the tour will be more useful once we have the full new editor. 

This should ideally use `{{@blog.url}}`
![image](https://cloud.githubusercontent.com/assets/120485/26653907/9e676aa0-464c-11e7-9581-4abb76952615.png)

![image](https://cloud.githubusercontent.com/assets/120485/26653936/b4a428f8-464c-11e7-8695-924c2016f966.png)

![image](https://cloud.githubusercontent.com/assets/120485/26653942/c1201984-464c-11e7-990b-6cb06a8ecd28.png)

![image](https://cloud.githubusercontent.com/assets/120485/26653952/cdd1ea72-464c-11e7-9a7b-952b14a374aa.png)

This one needs an actual URL to link to -- worth reviewing in docs task next week? 
![image](https://cloud.githubusercontent.com/assets/120485/26653968/dacdda6a-464c-11e7-8766-ff7005fa8e11.png)

**Comment by JohnONolan** [comment]
Sketch
[ghost-tour.zip](https://github.com/TryGhost/Ghost/files/1042947/ghost-tour.zip)

**Comment by nuclearpengy** [comment]
Looks great! :)

**Comment by JohnONolan** [comment]
- [ ] Throbber animation is broken. This is definitely not the code I wrote. It shouldn't be fading out completely or moving at a static speed
