### ISSUE TITLE
Middleware refactor: split files & improve test coverage

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5286]
This is loosely a part of the [frontend refactor](TryGhost/Ghost/issues/5091) that we need to do to make channels possible. 

---

###  The problem

Ghost’s middleware stack has evolved past the point where the current file structure is easily manageable. 

Originally we had 2 files: middleware/index.js which registers the middleware stack + contained a few middleware functions, all of which was considered not unit testable, and middleware/middleware.js which contained only middleware functions which were testable and had unit tests.

There is now >100 lines of code which sets up the middleware stack, much of it with undocumented inter-dependencies on the order things have to happen in. 

There is also ~700 lines of middleware functions in these two files, with very poor test coverage.

###  The solution

The immediate solution is to start splitting out middleware functions, or groups of related functions (like the spam prevention middleware) into separate files. 

Each middleware file should have a doc block which explains usage, any known before/after dependencies, and information on which app they belong to (blog, admin, api, or a combination?).  Each file should also be paired with its own test file with 100% coverage\*.

This is just the first step towards doing two things: 1) separating out the middleware that is global, from that which is only for the blog/admin/api apps in a more manageable way, and 2) using a different mechanism for setting up the stacks something akin to [express initialisers](https://github.com/jgable/express-initializers) or some sort of dependency injection. 

This task can be approached either all in one go if someone’s feeling brave, or alternatively with each piece of middleware done separately and referencing this issue, which make a few good small beginner issues. I have already done the cache control middleware as an example [here](https://github.com/TryGhost/Ghost/pull/5287).

The end result of this work should be no more middlware/middleware.js, and nothing left in middleware/index.js except the big stack registration. 

\* 100% coverage is not required as a general rule for Ghost, except in extremely important areas like the theme helpers, and middleware :) You can generate a coverage report by running `grunt coverage`

--- 

### Tasks

Simple pieces to move, but require unit tests:

- [x] middleware.js#authenticate
- [x] index.js#redirectToSetup
- [x] index.js#serveSharedFile
- [x] index.js#decideIsAdmin
- [x] index.js#uncapitalise

Unused & can be deleted:

- [x] middleware.js#whenEnabled 

Can be grouped into a file:

- [x] middleware.js#staticTheme, middleware.js#forwardToExpressStatic + helper functions
- [x] index.js#ghostLocals, index.js#updateActiveTheme + index.js#activateTheme & index.js#configHbsForContext (+ maybe decideIsAdmin?)
- [x] All private blogging middleware from middleware.js: checkIsPrivate, filterPrivateRoutes, authenticatePrivateSession, isPrivateSessionAuth, authenticateProtection + the verifySessionHash helper func.
- [x] All SSL related middleware from middleware.js: checkSSL, isSSLRequired, sslForbiddenOrRedirect
- [x] middleware.js#spamForgottenPrevention, middleware.js#spamSigninPrevention, middleware.js#spamProtectedPrevention
- [x] middleware.js#addClientSecret, middleware.js#authenticateClient, middleware.js#generateAccessToken

**Comment by ErisDS** [comment]
Have started populating a list of middleware that can be split out in this issue

**Comment by ErisDS** [comment]
I'm playing around a little bit with refactoring other bits of Ghost at the moment, and realised that a lot of the functions in middleware.js are registered as anonymous functions - meaning it's quite hard to debug/check what's going on.

Would really appreciate it if people working on splitting out middleware could make sure they name their middleware functions so that this problem goes away :)

This just means making sure that you do one of:

`return function myMiddlewareFunction (req, res, next) { ...`

`myMiddlewareFunc: function myMiddlewareFunction(req, res, next) {...`

` var myMiddlewareFunc = function myMiddlewareFunc(req, res, next) {...`

Thanks :dancer:

**Comment by ErisDS** [comment]
The list on this PR is now complete. There are roughly 8 groups of middleware remaining that can be split out.

`middleware#authenticate.js` is the highest priority of all these - would be awesome to get this one split out as it belongs to the API. This would be a step towards being able to look at #4172 and also would help with the ongoing work to provide public client access to the public endpoints.

**Comment by delgermurun** [comment]
Looks like this issue's checklist haven't updated quite a while or has it done already?

**Comment by ErisDS** [comment]
The tasks to split the middleware up are complete, the code coverage could still be improved:

![](http://puu.sh/kD2jI.png)

However, I think it's good enough now that this can be closed. Test coverage improving PRs are always very welcome.
