### ISSUE TITLE
[Zelda] Bugs, regressions and todos in master

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5314]
Thought I'd open an issue to cover / keep track of all the bits and pieces we know needs doing now that Zelda is merged.

## bugs & small issues
- [x] `.icon-check` and `.icon-chevron` have gone AWOL
- [x] Fix up sidebar nav #5313 / #5311
- [x] Private blog form #5073
- [x] 404 / error pages are ugly :(
- [x] Publish/Unpublish menu closes before you can choose an item 90% of the time (menu & popover conflict?
- [x] Notifications don't close after 5 seconds anymore (to be fixed in #5409)
- [x] Signup/on-boarding password validation requires 8 characters, input says 7.
- [x] Bugs on URL image uploader #5433
- [x] Settings routes don't redirect to signin #5412
- [x] Nav permissions #5403 
- [x] title overlap on content screen #5402
- [x] Vertical scrolling issue on settings screen #5401
- [x] Permissions for Team area #5434 
- [ ] localstorage / state for navigation
- [x] spin buttons #3928
- [x] Re-add multi-line placeholder #5459

## major issues
- [ ] Notifications refactor #5409
- [ ] Post/Tag/User auto-complete 'search' bar #5343 
- [x] Inline Validation #5336 
- [x] Re-implement the tag editing component #3800 
- [x] Roll out inline validation across the app (being done in #5409)

### user onboarding flow (Epic: #5315)
- [x] API: New 'PUT' version of `/authentication/setup/` #5342 
- [x] User Onboarding - wiring up setup & signup correctly #5339 
- [x] User Onboarding - Upload Profile Image Component #5334 - in progress by @acburdine (open PR #5355)
- [x] User Onboarding - Flow navigation component #5317

If you think you have found an issue we don't know about, drop a comment and it'll get added to the list.

**Comment by letsjustfixit** [comment]
Just two minor things:
  - 1 :IE 11 Forgotten password link is overlapped with an icon while writing (not a problem really just ugly)

![ghost_ie_password_forgotten_overlap](https://cloud.githubusercontent.com/assets/9042757/7785722/56a5bf78-019d-11e5-849a-66fc98a42bab.gif)

  - 2: Firefox 38.01 if you try to select a text inside an input field it still has the same style as before, just the cursor disappeares. Not an issue with chrome or ie11.

![ghost_selection_in_input_chrome_ff](https://cloud.githubusercontent.com/assets/9042757/7785723/56a89a72-019d-11e5-9aa1-9a691a0e8838.gif)

Tested Ghost version: commit 7190e1d2a302a3cc9c69a835ff3fac2f5b274fb3

**Comment by letsjustfixit** [comment]
Hey I've found another weirdness with ONLY firefox (38): no scrollbars in the settings page.
It's all good with Opera, Chrome, Vivaldi..

**Comment by morficus** [comment]
regarding the "select text" not not highlighting... it seems like this is the culprit: 
`background: lighten(var(--blue), 20%);` ([src](https://github.com/TryGhost/Ghost/blob/master/core/client/app/styles/patterns/global.css#L60))

`lighten()` is a LESS function... but Ghost is not using LESS. So the CSS that gets served up to the broswer looks like this: 
`
::selection {
  background: lighten(hsl(90, 80%, 50%), 20%);
}
`

**Comment by ErisDS** [comment]
Updated the OP here with an overview of outstanding issues & what's in progress, ready for today's meeting (cc @dbalders). One thing I'm not sure about is the current state of the navigation @JohnONolan & @novaugust ?

**Comment by ErisDS** [comment]
@JohnONolan if all the bugs in the comments here are sorted, then we can probably close this in favour of #5652 and have a separate issue to track adding localstorage tracking of the menu state? All the other items in here have their own issues.
