### ISSUE TITLE
Ghost Importer: Current State, Problems and Future Improvements

### ISSUE THREAD

**Issue by cobbspur** [TryGhost/Ghost#5422]
This Issue is to pick up where Issue #4605  left off and consolidate the issues surrounding the importer into one place. It is also to generate a conversation on what people would like/expect to see from the importer.
## Current State

As it stands the Importer can handle zip files containing images, markdown files and the official JSON formatted file but not raw JSON. It should probably be opened up to take raw JSON data as well.
## Problems

There is some feedback at the moment if the import fails such as a post with an unknown user_id but there are other cases where it simply says the import has failed with no other useful information so we need to investigate all possible causes of failure and display more information if possible.

There is currently no visual feedback of potential problems. We check the import file for posts and tags that have a matching slug, title or name but we do not display this information or compare it with the current posts and tags in the database which leads to duplications. This can be found as well in Issue #4685

There is no visual feedback of what the import file contained (I am about to make a PR for this to get the ball rolling - it is fairly rough and ready at the moment but better no information at all)

There are comments in the codebase about implementing a Dry-run. i.e. testing the import file, comparing with the current database then providing feedback to the user prior to actually performing the import. We could decide to complete the whole import process if no problems are found or have a check box to let the user see details of the import first either way such as number of posts etc.

The feedback could come with options on how to merge the data - e.g. for a duplicate post - the user could either:
- use current database version of post
- use importer version of post
- use both posts (incrementing onto current slug as currently happens)
- use post with most recent published_at/updated_at value

The UI needs some love as well. I was playing around with moving the importer into a modal. This is okay but I am not sure it is really required, perhaps the feedback would be nicer in a modal rather than the labs page. There was some discussion on the UI in #3927

Large import files can really mess with Ghost - presumably the import times out somewhere so this needs further investigation and either files have to be intelligently chopped up/chunked somehow.

There was also discussion at some point about creating an export or backup (more like the migrations backup) when importing - this could be automatic or provided as an option to the user and this is something I think is necessary for the delete content button. A Backup is probably better than export (maybe choose a limit on backups in the codebase or through the admin-UI). Discussion on this would be great - such as whether people agree or disagree and preferred approach if any.
## Future improvements
- It would be nice if we could have specific importers from various other platforms either via some automated check of the file/page or via a dropdown menu.
- Image acquistion - Checking through posts for images and downloading them automatically could be tricky but would greatly enhance the migration process.
- Create flows in modals or otherwise for users to fix through problems found - e.g. if posts have an unknown user_id they could see the users available and select one, or create a new user rather than having to dig into the import file.

## Required tasks
- [x] refactor the importer: right now we have two different folders for the importer logic - sort that out
- [x] improve logs and error information for the user
- [x] investigate import failures with no information
- [x] https://github.com/TryGhost/Ghost/issues/6967: tags loosing order after importing
- [x] https://github.com/TryGhost/Ghost/issues/7275: prevent sending notification to Slack when importing blog data
- [x] https://github.com/TryGhost/Ghost/issues/8349 
- [x] https://github.com/TryGhost/Ghost/issues/8365
- [x] Look at #4685
- [x] there were issues with duplicate posts_tags, authors with duplicate slugs and I think there was an issue where there were duplicate tags in the import file after sanitisation

## Optional/Future tasks
- [ ] add all weird edge cases as tests
- [ ] Image Acquisition
- [ ] https://github.com/TryGhost/Ghost/issues/8015: importing JSON database with wrong date format throws deprecation warning
- [ ] discuss/implement backups
- [ ] fix importer for large import files
- [ ] split the importer processing up to allow for a dry-run option
- [ ] provide more controls to user on how to merge duplicates
- [ ] warnings we can add: two users are imported with same email, but different slug (slug is regenerated)
- [ ] optimisation: trigger an export before import

**Comment by ErisDS** [comment]
@kirrg001 is this issue up to date? You fixed so many things with the importer already, I wonder if its worth closing this and waiting to see what problems people run into in the real world. Also we have both #8756 and #8517 open - all tracking remaining issues in the importer. I think we can reduce issue noise here 😁

**Comment by kirrg001** [comment]
Yeah it is up-to-date. I kept it open for future improvements - see list on top. But yeah agree, let's close it - if we want to add some more improvements from the list on top, we can still look it up here.
