### ISSUE TITLE
Zelda Mobile

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#5483]
- [x] When mobile, on content management screen, single tap should open post for editing in place of double tap. Actually at the moment no quantity of taps work on a mobile device.
- [x] When a new route loads, the mobile menu should close
- [x] Role label alignment is broken on small viewports
- [x] view-title being cut off in mobile browsers, looks like flex-grow issue
- [x] hit area on mobile menu button is too small
- [x] there is no mobile menu button on the about page
- [x] tap actions on user menu dropdown are inconsistent as fuck
- [x] sidebar nav items are too small
- [x] main header is too big
- [x] massive horizontal scroll when mobile menu is open
- [x] about page is cut off at the top in mobile safari
- [x] dropdowns need mobile positioning

**Comment by hoxoa** [comment]
Maybe [this](https://github.com/runspired/ember-mobiletouch) Ember addon can help with the single tap/double tap.
What do you think of using swipe gestures for the sidebar navigation, so a `left swipe` would open the left sidebar navigation?

**Comment by JohnONolan** [comment]
Swipes to open main nav and post settings menu would be pretty awesome

**Comment by dbalders** [comment]
^ oops, sorry about all the references, didn't realize that was happening

**Comment by kevinansfield** [comment]
The `ember-mobiletouch` addon has been replaced by [ember-gestures](https://github.com/runspired/ember-gestures) which looks awesome so I'm going to have a stab at using that to fix the mobile tap woes.

What's the status of the styling related issues?

**Comment by JohnONolan** [comment]
non-existent :see_no_evil: - if there are any of those you happen to want to do something with.. by all means
