### ISSUE TITLE
API: Joins / Relations overhaul

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5615]
This issue is a little bit of a mixed back, I need to brain dump some of the join/relation stuff that needs to be added / fixed.

- [ ] Allow for include of Posts from Tag or User endpoints
- [ ] Once public endpoint perms are in place properly (#5614) ensure that the inclusion of Posts adheres to the same policy
- [ ] Change `post_count` include on Tag endpoint to be `posts.count`
- [ ] Add `tags.count` to Posts endpoint and `posts.count` to Users endpoint
- [ ] Once public endpoint perms are in place properly (#5614) ensure that the inclusion of counts adheres to the same policy
- [ ] Overhaul next & previous post implementation so that it is possible to include `next.tags` and `next.author` etc (fix #5150)
- [ ] Consider adding support for relations between users and tags through posts, e.g. listing tags for an author, or listing authors for a tag - although this is probably something for a later version.

**Comment by ErisDS** [comment]
# Count handling
- [ ] Change `post_count` include on Tag endpoint to be `posts.count`
- [ ] Add `tags.count` to Posts endpoint and `posts.count` to Users endpoint

I'm currently looking at how to implement counts across the posts / tags / users endpoints, and so I wanted to clarify a proposal for what they look like.

Inline or 'included' counts are counts which are requested in addition to other data, e.g. requesting all tags and also asking for a post count at the same time: `GET /tags/?include=posts.count`

Included counts in this form are mainly useful for two purposes that I can discern:

1. Providing an idea of how much data there is where the data has not yet been fetched, E.g. Having a list of Authors with an indication of how many posts each author has written. 
2. Ordering result sets by those that have the most related data, E.g. ordering tags by how many posts have that tag.

When making a `browse` request, the API automatically returns a count of how many items have been requested and how many exist in the full set (i.e. if the result is paginated) so it is easy to get a count of data that has been fetched. The key aspect of included counts is that they return information about related objects.

One of the complexities of including related counts, is needing to count the right things. E.g. when returning a "post count" along with tags, in the admin panel this would need to return the count for all posts, but when making this same request from the theme/frontend/public access the expectation is that it would only count 'published' items.

There are similar rules for active vs inactive users and private vs public tags (not implemented yet).

The main question on my mind is whether we should have a single syntax for requesting counts which automatically returns the full count of the data the requester has permission to access, or whether the requester should be able to specify what they expect. That is, should the handling of public vs private data be implicit or explicit?

## Implicit example:

Single syntax:

`GET /tags/?include=posts.count`

When the request comes from an authorised request (e.g. from the admin panel) the full count would be returned.

When the request comes from a public client (e.g. from the get helper or ajax in a theme) only published posts would be included.

Pros: 
- No thought on the users part is required to get hold of private data
- Single, simple syntax for requesting counts

Cons: 
- There is no way for an authorised user to get a public count
- This doesn't match a normal posts request, which by default would only ever return published posts unless the user specifies otherwise

## Explicit example:

Public data syntax:

`GET /tags/?include=posts.count`

Include private data syntax:

`GET /tags/?include=posts.all.count`

The default `posts.count` syntax always includes only the default 'public' information - published posts, active users, public tags. The extra qualification of `posts.all.count` includes all the data.

In this case, the 'all' qualification in the syntax always refers to 'public' vs 'all' data. This is a concept that we need to wire up more explicitly through the API as it applies to all 3 of our main resources. 

Pros:
- API users can be explicit about whether they're asking for public or all data. 
- This more closely matches how the API works in general (public by default, other data by request)

Cons:
- Requires extra thought about what data you want counted
- Extra syntax, although the same for all resources, could be confusing.

Although there is no way to specify count differences based upon other criteria (like whether a post is a page, or featured), I think there are sensible solutions to this. For pages, we should start to treat these as first class citizens in the API, providing `GET /pages/` and `pages.count` etc. 

For featured posts, or other more complex combinations, a separate request would need to be made.

The alternative to using `all` would be to used names like `posts.published.count` however, I think this would be potentially more confusing. If there's need for more count options in future we could extend from `all` to other 'named' counts, but if we add more complex names it will be hard to go back and remove them.

## Summary / TLDR;

I am leaning heavily towards the explicit `posts.count` and `posts.all.count` version, because it matches the way the browse request works and makes it possible to request both public and all data when making authenticated requests, which would otherwise not be possible.

We're looking at making public vs private data handling more implicit inside of read requests as discussed in #5947, which makes sense because the user is already making an explicit request for a particular resource. I don't think the same idea works here.

----

Note: The API does not currently support doing requests which are only intended to return a count, and nothing else, although this can be simulated by only requesting `fields=id`. If there is a strong need for fetching just counts this behaviour could be added later.
