### ISSUE TITLE
i18n: harvesting server-side strings

### ISSUE THREAD

**Issue by morficus** [TryGhost/Ghost#5617]
## The Problem
Ghost is currently pretty much UK-based English-language only, and has barely any features to account for timezones, locales, languages, alphabets, keyboard layouts or anything else that isn't UTC/English in either the admin or in themes. Even the USA folks luck out, sorry! All this is set to change with full support for multiple locales and languages across the admin and your blog posts. [[src](#3801)]

## The Solution
(see #5345 for full details)

The first phase of the multi-part rollout is to remove all strings that are hard-coded in the app and put them in a centralized location (referred to as "harvesting"). At the end of phase 1 English would still be the only language supported in Ghost and there would be no noticeable change to the end-user, but it will put things in a place where translations can start taking place.

But this is a big job and no one person can do it all alone (unless you're brave and have lots of free time)!  
Each piece of the string harvesting can be done separately and referencing this issue, which make a few good small issues for either beginners or folks that want to contribute but may not have a lot of time free time.

This commit is to help demonstrate how to go about harvesting strings and replacing it with the proper i18n function: https://github.com/morficus/Ghost/commit/a1559cde068f1861bf672e66ef2354c4d1fb6288

(PS: This particular issue is focused only on harvesting string that are server-side. There will be another issue for client-side strings.)

## Tasks
To grab a task, just leave a comment below indicating which you will be working on.

Places that have lots of strings across many files:

* [ ] /core/server/api
* [ ] /core/server/data

Places with a healthy amount, but not too many files:

* [ ] /core/server/models
* [ ] /core/server/helpers
* [ ] /core/server/middleware
* [ ] /core/server/apps

Places that have a small amount of strings that need harvesting:

* [ ] /core/server/controllers
* [ ] /core/server/config
* [ ] /core/server/permissions
* [ ] /core/server/utils
* [ ] /core/server/ghost-server.js
* [ ] /core/server/index.js
* [ ] /core/server/mail.js
* [ ] /core/server/require-tree.js
* [ ] /core/server/update-check.js

**Comment by rfpe** [comment]
I'm working on  /core/server/mail.js,  /core/server/update-check.js and /core/server/index.js.

**Comment by rfpe** [comment]
Working on /core/server/require-tree.js and /core/server/ghost-server.js

**Comment by rfpe** [comment]
Working on  /core/server/config/*,  /core/server/permissions/* and  /core/server/utils/*
Pending: /core/server/controllers/*

**Comment by ErisDS** [comment]
@rfpe if you're taking on multiple sections it would be great if you could open a WIP PR :+1:
