### ISSUE TITLE
Zelda Audit

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#5652]
Followup of #5314

ALL TESTED IN SAFARI 8.0.7 for OSX - I am actively working on these issues

- [x] Broken publish menu position [image](https://www.dropbox.com/s/tlzbnb92w9r4ftn/Screenshot%202015-08-11%2009.27.58.png?dl=0)
- [x] Dropdown shadow too heavy [image](https://www.dropbox.com/s/vtt1h6xq0jforxv/Screenshot%202015-08-11%2009.29.01.png?dl=0)
- [x] "Team" is lowercase and author name is cut off, on author profiles [image](https://www.dropbox.com/s/enm9dw3q464ro7u/Screenshot%202015-08-11%2009.31.24.png?dl=0)
- [x] Button alignment and button text alignment are wrong on author cover image upload modal [image](https://www.dropbox.com/s/4s5uvj9e4lx8wal/Screenshot%202015-08-11%2009.32.14.png?dl=0)
- [x] Loading buttons are not centered
- [x] No indication that saving settings has succeeded
- [x] "View blog" contrast too low
- [x] Full name should align with fields below [image](https://www.dropbox.com/s/pleqgee9ljrc6dl/Screenshot%202015-08-11%2009.38.45.png?dl=0)
- [x] Button text alignment on invite user is wrong [image](https://www.dropbox.com/s/12aftfc4ivbh50l/Screenshot%202015-08-11%2009.39.44.png?dl=0)
- [x] Invitation confirmation should be a notification rather than an alert [image](https://www.dropbox.com/s/5mxtultlph8yejr/Screenshot%202015-08-11%2009.40.51.png?dl=0)
- [x] There is no indication of any kind when you "resend" and invitation
- [x] Unstyled validation on settings/general [image](https://www.dropbox.com/s/vuxn780stm1e4o1/Screenshot%202015-08-11%2009.43.11.png?dl=0)
- [x] Subsequent error loop of death [image](https://www.dropbox.com/s/2xou2iw1dbushqy/Screenshot%202015-08-11%2009.43.47.png?dl=0) / [console](https://www.dropbox.com/s/uzjt2zod4h85q4f/Screenshot%202015-08-11%2009.45.04.png?dl=0)
- [x] Further saves of settings/general do nothing
- [x] Contrast on tag description too low [image](https://www.dropbox.com/s/6g5bcnz8pm3x2zi/Screenshot%202015-08-11%2009.46.31.png?dl=0)
- [x] Settings menu image upload-by-URL button alignment is wrong [image](https://www.dropbox.com/s/qflwdtb0ofj7v1u/Screenshot%202015-08-11%2009.47.05.png?dl=0)
- [x] Meta data submenu missing right-chevron on tag-settings-menu [image](https://www.dropbox.com/s/m1obs5iuije1m22/Screenshot%202015-08-11%2009.47.40.png?dl=0)
- [x] Tried to save user after changing role from author=>editor, infinite loading button, nothing happened
- [x] For some reason clicking anywhere in the content highlights the entire thing [image](https://www.dropbox.com/s/17hrh910dgvm1fw/Screenshot%202015-08-11%2009.50.57.png?dl=0)
- [x] validation causing forms to load with green icons (should be grey) [image](https://www.dropbox.com/s/d0g0fn08gfib7ek/Screenshot%202015-08-11%2009.54.33.png?dl=0)
- [x] Signin form should not be validating inline if field is empty [image](https://www.dropbox.com/s/1qscel0dnahxtp5/Screenshot%202015-08-11%2009.55.35.png?dl=0)
- [x] Not enough space for validation on signin form [image](https://www.dropbox.com/s/1qscel0dnahxtp5/Screenshot%202015-08-11%2009.55.35.png?dl=0)
- [x] Editor frequently ends up in a state where the loading button is permanently spinning for no reason when you open it. Seems to happen when a loading spinner has stalled out or messed up on a previous screen. [image](https://www.dropbox.com/s/wmw866rklr3apt2/Screenshot%202015-08-11%2009.57.38.png?dl=0)
- [x] "Edit icon" on content management screen should not have an :active / depressed state
- [x] Hit area on the ? icon is WAY too small
- [x] Can't actually sign in at all on Chrome - [licecap](https://dl.dropboxusercontent.com/u/453148/Licecap/signin.gif) - [terminal](https://www.dropbox.com/s/gihwhsqbv1l5p5k/Screenshot%202015-08-11%2010.14.00.png?dl=0) - [console](https://www.dropbox.com/s/w5qhhar6hu64nyx/Screenshot%202015-08-11%2010.14.45.png?dl=0) (when I then manually refreshed, I was already signed in)
- [x] AutoNav flickering - [safari](https://dl.dropboxusercontent.com/u/453148/Licecap/menu-safari.gif) / [chrome](https://dl.dropboxusercontent.com/u/453148/Licecap/menu-chrome.gif)
- [x] The width of the publish button is being set with JS (why?!) which is breaking whenever the content changes [image](https://www.dropbox.com/s/aygs2ir3tpe6wva/Screenshot%202015-08-13%2009.03.08.png?dl=0)
- [x] Publish button height has regressed [image](https://www.dropbox.com/s/uu6zl1w03xk53pb/Screenshot%202015-08-24%2013.06.36.png?dl=0)
- [x] CMD+Backspace does not work to delete a post in safari (content mgmt screen)
- [x] Tag input has unintentional box shadow [image](https://www.dropbox.com/s/cdyb9d22mgu39js/Screenshot%202015-08-24%2016.26.29.png?dl=0)
- [x] The download count on setup is incorrectly formatted (needs comma) [image](https://www.dropbox.com/s/zb07nvrjmwd9kgr/Screenshot%202015-08-25%2010.23.57.png?dl=0)
- [x] Do not validate empty form fields on setup [image](https://www.dropbox.com/s/mkrza15dgabrrrv/Screenshot%202015-08-25%2010.25.12.png?dl=0)
- [x] Pressing "tab" after the last input field takes keyboard focus to address bar. Should be: submit button. [image](https://www.dropbox.com/s/9g9puteifgkx8w5/Screenshot%202015-08-25%2010.26.52.png?dl=0)
- [x] User invite validation should be properly coloured [image](https://www.dropbox.com/s/9iyqz4mt8bqpn2n/Screenshot%202015-08-25%2010.27.49.png?dl=0)
- [x] Validation message does not disappear even though I have fixed it [image](https://www.dropbox.com/s/wo9o29vw4smr47z/Screenshot%202015-08-25%2010.29.08.png?dl=0)
- [x] Can we inject that validation message into the button instead of under the textarea?
- [x] "Failed to send 1 invitationS ? Come on now. Aside from bad grammar, this also needs to be more helpful and offer a suggestion as to why this might be the case. [image](https://www.dropbox.com/s/hrt616htj7laroh/Screenshot%202015-08-25%2010.30.58.png?dl=0)
- [x] Duplicate alerts should not stack [image](https://www.dropbox.com/s/6r4tjnvdj8awiso/Screenshot%202015-08-25%2010.31.29.png?dl=0)
- [x] When I click back to step 2, my password field is empty and validation is red. Now I don't know if I need to enter this again, or not? Has this step already been completed? Do I have to do it again? Genuinely confused, and I know how this works, roughly! [image](https://www.dropbox.com/s/mlhg1k411x4sw2x/Screenshot%202015-08-25%2010.32.22.png?dl=0)
- [x] Hang on, what instructions? Why do I need instructions? [image](https://www.dropbox.com/s/qlj78bozz9heumy/Screenshot%202015-08-25%2010.33.42.png?dl=0)
- [x] Clicked on "forgot password" and then nothing happened, at all, except the button disabled itself. What am I supposed to do now? (Also, clearly it couldn't send the email, I haven't got any mail svc configured) [image](https://www.dropbox.com/s/a9nuqvuwxo6c7sb/Screenshot%202015-08-25%2010.35.14.png?dl=0) -- oh, after like 10 mins this appeared [image](https://www.dropbox.com/s/icfoigbo10cls3b/Screenshot%202015-08-25%2011.00.21.png?dl=0)

### By Hannah

- [x] ~~gravatar behaviour doesn't fire until blur~~ moved to #5797
- [x] skip to content link doesn't work [detailed comment](https://github.com/TryGhost/Ghost/issues/5652#issuecomment-134717270)
- [x] need to hide search bar
- [x] using tab navigation on tag page TSM causes meta menu to half-open [image](http://puu.sh/jOlPO.png) - reproduce by putting cursor in name field and tabbing until you see this.
- [x] session expiry issues
- [x] ~~loading interstitial & pre-app loading screen~~ moving to post-zelda
- [x] double click to open post not working on content screen
- [x] No validation on user invites

### Loading buttons: Don't know how to solve

When an action takes more than 1s, the loading spinner makes sense in a button. But when an action takes 0.1s - adding/removing a loading spinner makes the button feel broken. I think we need a mandatory "success" animation which can follow the loading animation when the route is not changing. I don't think this is going to be easy.

Also: When logging in, the loading button stops spinning before the admin loads. This should not happen. It should keep spinning all the way until the route changes without ever stopping

## Mobile

All tested on latest Chrome for iOS

- [x] Small viewport: title cut off [image](https://www.dropbox.com/s/57trbmqi1plmkyi/Screenshot%202015-08-11%2010.02.50.png?dl=0)
- [x] Mobile menu should close on route change
- [x] "Collapse sidebar" icon should also close mobile menu
- [x] Mobile menu hit area too small
- [x] Horizontal scroll/overflow when mobile menu is open
- [x] Can't edit any post (when you tap on post in content mgmt, nothing happens)
- [x] Need a way to trigger mobile uploads

**Comment by acburdine** [comment]
@JohnONolan the reason the width of the publish button is being set with JS is because when the spinner is activated on post save, the width of the button will shrink to the size of the spinner. This can be removed; however, I didn't have any other good ideas on what to do to prevent the button from shrinking when the spinner is active.

**Comment by JohnONolan** [comment]
@acburdine The way we handle this on Ghost.org is that when a loading-button is clicked:

1. The width of the button is retrieved with jQuery
2. The width of the button is set to itself with jQuery
3. The text of the button is replaced with the span of the loading element with jQuery

(so width is only fixed when it needs to be, not all the time)

**Comment by acburdine** [comment]
@JohnONolan ah gotcha. That's kind of the way I was doing it, but not exactly, so I'll PR a fix to it.

**Comment by kevinansfield** [comment]
> Can't actually sign in at all on Chrome

I've just seen the same issue in Safari too

**Comment by ErisDS** [comment]
Something I've noticed - the behaviour of the gravatar tied to the email fields on setup & signup changed, such that the gravatar request isn't fired until the field is de-focused. This doesn't give the same instant effect it had when it was first implemented. The change was to reduce the number of requests made, but I think this can be improved to only fire the request if the email is valid?

This is probably something that can be improved across the inline validations as well - such that invalid states on fields get removed when you start typing in them again?

Also not mentioned here - is the search bar ;)

**Comment by ErisDS** [comment]
Also note: there is a separate open issue about the spin button disappearing too quickly on sign-in: https://github.com/TryGhost/Ghost/issues/5650

**Comment by kevinansfield** [comment]
> I think we need a mandatory "success" animation which can follow the loading animation when the route is not changing. I don't think this is going to be easy.

It should be relatively easy to pass in a success/failure status to the spin button component which can then react accordingly by changing colour/showing a checkmark/whatever before reverting to it's base state after a timeout.

**Comment by kevinansfield** [comment]
> Hang on, what instructions? Why do I need instructions? image

Is re-stating the URL here a bit redundant? You need to read the console output and manually enter the URL in order to reach the page that shows this alert.

**Comment by JohnONolan** [comment]
> It should be relatively easy to pass in a success/failure status to the spin button component which can then react accordingly by changing colour/showing a checkmark/whatever before reverting to it's base state after a timeout.

Would you be able to have a look at this? This is exactly the area where CSS and JS making out with each other confuses the hell out of me. For reference: The Slack team admin save buttons are an absolutely perfect representation of how this could/should ideally work.

**Comment by JohnONolan** [comment]
> Is re-stating the URL here a bit redundant? You need to read the console output and manually enter the URL in order to reach the page that shows this alert.

Yeah, I think this entire message is probably better suited to the console - thinking about it

**Comment by kevinansfield** [comment]
> Would you be able to have a look at this? This is exactly the area where CSS and JS making out with each other confuses the hell out of me. For reference: The Slack team admin save buttons are an absolutely perfect representation of how this could/should ideally work.

Sure, I'll raise a separate issue to track it. Is the attached gif the desired behaviour? (taken from Slack's website - no idea if that's different to the team admin)

![slack-save-button](https://cloud.githubusercontent.com/assets/415/9463561/3fe35798-4b15-11e5-9c6c-38cfa2165464.gif)

**Comment by JohnONolan** [comment]
Yes that's the one :)

**Comment by ErisDS** [comment]
> Hang on, what instructions? Why do I need instructions?

That 'first run' message is there to direct people to instructions on configuring their URL, mail & switching envs etc - it's less important now than it was when it was originally added (I think it's been there since the prototype :wink:) - do you wanna change or remove it? It does not appear on Ghost(Pro).

**Comment by JohnONolan** [comment]
Yeah kill completely I think

**Comment by ErisDS** [comment]
> Yeah kill completely I think

Happy to do this (is super quick). Just wanted to do a sanity check - do we not want to have any 'first run' message any more? Just to clarify, this message appears on all self-installs, and says which env & url the user is running on, as well as pointing to support.

I fully agree the current message isn't useful - the console & about page both tell you which env you're on now, and telling the user what their URL is on first run is totally redundant. Soooo before I whip this out entirely, just wanted to check we wouldn't like some other shiny greeting to appear on the first run?

**Comment by ErisDS** [comment]
> Pressing "tab" after the last input field takes keyboard focus to address bar. Should be: submit button.

^ am working on this one

Whilst working on that, I noticed the accessibility skip-link doesn't seem to work presumably because there is nothing with id `gh-main` - should the element with role `main` have that id?

**Comment by ErisDS** [comment]
I've moved my comments into the task list in a section called 'By Hannah' feel free to edit / remove any items that are wrong

**Comment by ErisDS** [comment]
> Signin loading with green icons (should be grey)

This is true across all flows with inline validation. What are the rules? Should it be grey unless there is an error, and then be red or should it be grey by default, go red on error or green on success?

Are there any cases where icons should be green? 

Trying to figure out whether this is a CSS problem or a validation system problem.

**Comment by ErisDS** [comment]
>  CMD+Backspace does not work to delete a post in safari (content mgmt screen)
It seems to me that in safari you have to click once to give focus to the content, and then navigating around, cmd+backspace and the other shortcuts work. By default something else has focus. No idea what the issue is here but suggesting it be classified as 'safari edge case'.

**Comment by JohnONolan** [comment]
> What are the rules? Should it be grey unless there is an error, and then be red or should it be grey by default, go red on error or green on success?

Exactly what was in the original spec, mockups, and discussion - thoroughly documented.

1. Default is grey
2. Success is green
3. Fail is red

**Comment by JohnONolan** [comment]
> Soooo before I whip this out entirely, just wanted to check we wouldn't like some other shiny greeting to appear on the first run?

Yep kill it

**Comment by kevinansfield** [comment]
This may be an iOS 9 thing but on my iPad the screen height is greater than the viewport height which means scrolling sometimes feels a bit odd and you need to scroll down to see the collapse menu and view blog buttons.

**Comment by JohnONolan** [comment]
@kevinansfield I have a rough idea of what you mean, but I'm not 100% certain -- mind posting a screenshot?

**Comment by ErisDS** [comment]
Note: Have moved the two checkbox related items to #5728

**Comment by kevinansfield** [comment]
@JohnONolan sorry forgot my lightning cable so no video but screenshots show scrolled to top and bottom

![image](https://cloud.githubusercontent.com/assets/415/9494960/d3d1db28-4c00-11e5-95c6-bf7647921d4a.png)
![image](https://cloud.githubusercontent.com/assets/415/9494961/d3f697d8-4c00-11e5-95ae-4ff90337e2c0.png)

**Comment by kevinansfield** [comment]
> Can we inject that validation message into the button instead of under the textarea?

@JohnONolan Could you expand on that a bit? I'm struggling to visualise how it would work, especially if the incorrect e-mail address is quite long (see image)

<img width="427" alt="screen shot 2015-08-27 at 11 00 27" src="https://cloud.githubusercontent.com/assets/415/9517893/e65d0b82-4caa-11e5-852b-3182503f929c.png">

**Comment by JohnONolan** [comment]
@kevinansfield `[n] invalid email address(es)` ?

**Comment by kevinansfield** [comment]
That's do-able, are we ok with losing the information about which e-mail is invalid? I could see that being useful if pasting in a list of e-mails but I have no idea how frequent that use case is.

**Comment by JohnONolan** [comment]
I think probably infrequent enough to be safe, let's run with it until someone complains?

**Comment by kevinansfield** [comment]
Ok, I'll update #5735 with the changes. Does the button need any visual changes if it's invalid?

**Comment by JohnONolan** [comment]
I think it can just stay in its grey/deactivated state

**Comment by ErisDS** [comment]
Items are all checked off!
