### ISSUE TITLE
Tag Management UI Updates

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5845]
Following on from Zelda, there are a number of improvements and changes surrounding tag management that would be great to do:

### In Settings / Tags:

- [x] Use routes for the tag settings screen. This should work such that each tag has a navigable URL e.g. ghost/settings/tags/getting-started and when navigating to that URL the tag settings menu is already open displaying that post. (#5969)
- [x] When navigating to a tag URL, that tag should also be automatically selected in the left list (like posts on the content screen) (#5969)
- [x] Add validation to the description field in the tag settings menu (200chars max) (#5865)
- [x] Add the 200 char countdown underneath the description field in the tag settings menu (#5865, #5952)
- [x] Add validation to the slug field in the tag settings menu (200chars max) (#5952)
- [x] Keep the settings pane open, and allow users to click between tags in the list on the left hand side (again, like the content screen) (#5969)

I believe there is also some work needed to improve how the models are bound here which may or may not fall out automatically as a result of switching to using routes.

### Search:

- [x] Once tags have a route, add tags to the autocomplete admin search (#5991)

### Post settings tag component:

- [x] Add drag and drop reordering of tags - this requires an upstream fix I believe. (#6010)
- [x] Revisit when / how tags get saved? (save on blur?)

### Bonus

- [x] Add `<site>/tag/foo/edit` redirect to send users from the frontend of the blog to the tag management screen (#6011)

**Comment by novaugust** [comment]
I'd like to add `<site>/tag/foo` should have a redirect on `<site>/tag/foo/edit` to the new route on the settings screen you're talking about :D

**Comment by ErisDS** [comment]
:+1:

**Comment by acburdine** [comment]
On that same thread, since authors are also a first-class resource, would it be a good idea to also allow `<site>/author/foo/edit`?

**Comment by kevinansfield** [comment]
> I believe there is also some work needed to improve how the models are bound here which may or may not fall out automatically as a result of switching to using routes.

@ErisDS, @JohnONolan: Is the desired behaviour here that nothing on the main screen changes whilst typing in a settings field until that field is saved?

**Comment by kevinansfield** [comment]
> Revisit when / how tags get saved? (save on blur?)

This has been partially revisited in that the "scratch" properties are now self contained within the `gh-tag-settings-form` form component which leaves the controller clean as it only has to deal with `setProperty` actions that are raised from the component. `setProperty` and the resulting save of tag models are currently only triggered on blur.

Was there something else that needed to be addressed here?

**Comment by ErisDS** [comment]
> Was there something else that needed to be addressed here?

I only wrote that bullet point because you had said something about wanting to change those things, I had nothing in particular. 

I think we can count this issue as complete?

**Comment by kevinansfield** [comment]
Ok cool, that can definitely be marked as complete then.
