### ISSUE TITLE
Public API v1 Sprint Epic 

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#5976]
## Public API

We've been talking for a very long time about making our JSON API publicly accessible via OAuth (See the [OAuth Epic](https://github.com/TryGhost/Ghost/issues/4004)).

The plan is to make this a reality in the next release but in a limited way: The read-only public endpoints will be made available to themes via the `{{#get}}` helper and also to public clients, but without a UI for registering new clients. This means that it will be possible to use the API via ajax from within themes as well as the get helper, in order to fetch what we consider 'public' data - published posts, tags, and active users. This will be considered a 'public beta' of the API. 

As well as making the data accessible, we need to push to clean up the API and ensure that the available endpoints are truly useful. The following are a set of must-have and nice-to-have API changes:

Ready:
- [x] Validation (issues #2756 & #2758) 
- [x] Make the 401 error format consistent (#5499)
- [x] Add `fields` parameter (issue #5601)
- [x] Add the `filter` parameter (issue #5604)
- [x] Move top level browse params to `filter` (issue #5463)
- [x] Add `order` parameter (issue #5602, ref #5463)
- [x] Remove auth from public endpoints (#4181)
- [x] Implement auth for public clients with a client id (#4180)
- [x] Default client entry (#4184)
- [x] Initial get helper (#4439)
- [x] Update get helper to work with Filter param (Issue #5993) 

Nice to haves:
- Finish 'pipeline' refactor (#5508)
- Joins & relations cleanup (issue #5615)
- Cross table ordering (#6008)
- Cross table count handling (inc ordering) (#6009)
- Improve the has helper (issue TBD)
- Complete rewrite of page support

Needed for release:

- [x] No more staticPages parameter (#5151, requires #5604) `sebgie`
- Public permission handling (#5614), at least: 
     - [x] ensure count doesn't return wrong value `erisds`
     - [x] ensure filter cannot be abused to get private data `erisds`
- [x] Add labs checkbox for public API access (PR #5984)
- [x] Move get helper behind labs flag (no issue)
- [x] API helper for ajax requests (#5942) `not assigned`
- [x] API docs (#5588) `cobbspur`
- [x] Get helper docs `cobbspur`
- [x] Revisit origin validation #6106

Other API issues to consider:

- Improve error messages 
- Figure out what to do with versioning
- Slashes in API endpoints?

## Other Sprint Items

- Tag Management UI Updates (issue #5845)
  - [x] routable tags UI (PR #5969)
  - [x] add tags to search (PR #5991)
  - [x] drag-n-drop tag re-ordering when editing post (PR #6010)
  - [x] `tag/:slug/edit` redirect (PR #6011)
