### ISSUE TITLE
Convert casper tests to ember acceptance tests

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#6039]
Now that the casperjs tests have been switched off and quickly breaking as they are no longer being maintained we should aim to replicate the high-level tests in Ember.js.

Ember acceptance tests are a lot easier to reason about than the casperjs tests as they offer a number of [helpers](http://guides.emberjs.com/v2.1.0/testing/acceptance/#toc_test-helpers) with knowledge of Ember's run loop and other async operations to make testing smooth. [ember-cli-mirage](http://www.ember-cli-mirage.com) further eases testing by exposing a mock api with easy to use factories that allow you to quickly set up sufficient data for each test.

Guidelines for good acceptance tests:
- Test the basic list/get/create/update/delete flows of each area.
- Only test high-level features/interactions. Check that the core elements are rendered to the page and work through any flows that require transitions/redirects/modals etc. It should be expected that component integration tests will cover the details of components and their UI/interactions so they can safely be ignored in acceptance tests.
- Test infrequently-used flows, they are the ones most likely to be missed when checking PRs and can easily regress.
- Try to test as much of a flow within one `it` test as possible. Booting up a new application instance is expensive and slow tests were one of the main reasons we abandoned casperjs. If you need to test a different set of data or override mirage endpoints then that's a good indication that a new `it` should be used.

**Tip:** When working on a particular test you can limit ember's test server to only the test(s) that you are interest in by supplying a filter, e.g. `ember test -s -f 'Acceptance: Settings - Tags'`

TODO:
- [x] set up ember-cli-mirage and convert existing acceptance tests from base pretender to mirage (#6033)
- [x] test setup flow (partial tests in #6076)
- [x] test sign in flow (#6524)
- [ ] test password reset flow (partial tests in #6426)
- [ ] test sign up flow
- [ ] test content screen flows (@ErisDS)
- [ ] test editor flows
- [x] test team flows
- [x] test settings/general flows (#6482)
- [x] test settings/navigation flows
- [x] test settings/code injection flows (#6486)
- [ ] test labs flows (#6488, labs checkboxes tested via component integration tests)
  - [ ] test `sendTestEmail` flow

**Comment by ErisDS** [comment]
Putting my hand up for the content screen section - I really want to do at least one part of this so that I can fully get my head around the tools we're using 😊

**Comment by acburdine** [comment]
@ErisDS do you still want to do the content tests? To fully test the internal tags behavior there needs to be at least basic content tests in place, although those content page-specific tag tests could just be added later if you still want to do them 😄

**Comment by ErisDS** [comment]
Sorry - I should definitely put my hand back down here 😉

**Comment by ErisDS** [comment]
@kevinansfield do we really need this open still? 😬

**Comment by kevinansfield** [comment]
No, I think that can be closed now 😁 Most of the unchecked items have tests now and I don't think it's realistic to expect this issue to be remembered when improving test coverage in the course of normal development 😬
