### ISSUE TITLE
Sprint Epic - 10th Nov - refactoring & cleanup

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#6062]
Wrap up Public API Sprint Epic: #5976 (5 items)

Other Blockers for release:

- [x] Regression: Export throws 'access denied' #6040
- [x] Regression: No re-auth modal when saving editor with invalid session #6048
- [x] Regression: Not redirected to sign-in with invalid session #6047

---- 

This sprint:

- [ ] modal refactor #5798 @kevinansfield 
- [ ] acceptance tests - add outline files for each screen and fill in mirage config #6039 @kevinansfield 
- [ ] save buttons #5719 @kevinansfield 
- [ ] Joins & relations cleanup  #5615 @erisds

**Comment by ErisDS** [comment]
Closing this as I think it has served its purpose for the time being :)

**Comment by delgermurun** [comment]
@ErisDS you haven't closed it yet :).

**Comment by ErisDS** [comment]
Doh
