### ISSUE TITLE
Sprint Epic 8th Dec - 12th January

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#6191]
For 0.7.3 (to land asap):

- [x] `{{tags}}` and `{{foreach}}` helper improvements (#6205)
- [x] Publish date bug fix (#6184)
- [x] Reduce no. async helpers to reduce the no. cases that cause `aSyNcId`'s to be output (#5850)
- [x] Editor bug where certain chars can't be typed (#6192)
- [x] PR review

Post 0.7.3:

- [x] Data migration for hidden -> hashtag (#6165)
- [ ] Addition of client permissions + any others (maybe themes) (#4176)
- [ ] First pass at hash tags (#6165)
- [x] Remaining `{{tags}}` and `{{foreach}}` helper improvements

The remainder of the Sprint / Holiday period will be used to spike/experiment with the following things:

- new editor
- advanced image features (better upload, optimisation, management, and more)
- post filtering in the admin

The next Sprint hangout meeting will be on the 5th January.

**Comment by ErisDS** [comment]
Closing this in favour of https://github.com/TryGhost/Ghost/issues/6328

**Comment by ErisDS** [comment]
Also... we got 2 more bug fix releases done than we expected... not bad :cookie: :doughnut:
