### ISSUE TITLE
Database schema & fixtures migration v005

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#6301]
Several of the new features we want to add require us to make changes to the schema & fixtures, so we're going to need to setup a new data migration.

Doing this for Ghost is not as easy as we'd like, but then again, we don't do it very often atm, so optimising this process isn't high priority. Still, for this migration, we need to make some changes and improvements to the system as well as the migration itself.

This issue documents two sections of changes: must-haves and nice-to-haves. It's basically a log of all the outstanding issues with data and fixtures that we should change if we can, as well as the things we *have* to do for upcoming features.

## Must haves

These things need to be done for 005:

### Schema

- [x] add posts.mobiledoc - this is for the new editor spike #6255
- ~~add posts.is_private - this is speculative, as there's high demand for certain posts being private~~
- ~~change tags.hidden to tags.hashtag - this is for #6165~~
- [x] remove `hidden` from tags
- [x] add `visibility` as a small string that defaults to 'public' to posts, tags & users 
- [x] move the fix for the client secret from migrations/index.js into a migration for 005
- [x] Add facebook & twitter fields to `user` (see #6534)
- [x] Add facebook & twitter default settings (see #6534)

### Fixtures

- [x] client API permissions (refs #4175, #4176,  and #4177)

### Code changes

- [x] Make it possible to remove a column (requires #6103)

## Nice to haves 

It would be great if we could also do these things:

### Schema

- [ ] client_trusted_domains table should ideally have timestamps, not sure if these can be easily added as we don't have values for existing entries.
- [ ] look at fixing slugs which contained `{`, `}` or \` - not sure if this is a good idea as it would break old posts
- [ ] fix the field lengths #4134, #6471 (maybe set markdown, mobiledoc & html to be long as well)

### Fixtures
- [ ] theme API permissions
- [ ] config API permissions
- [ ] audit any remaining missing API permissions (apps?)

### Code changes
- [x] Review the idea of switching to knex migrations: #4824
- [x] Review the issues here: #4479
- [x] Add tests for migrations
- [x] Code cleanup/improvement around migrations & fixtures (smaller functions, clearer naming, etc)

Inside the /data/ folder the migrations, fixtures, utils and versioning folders all contain code which is almost exclusively to do with upgrading the data version (data migration). 
- there's probably a more sensible way to structure these files
- migration/commands.js and utils really don't make sense as a structure
- migration/index.js contains monolithic functions which could be broken out, renamed, made smaller and clearer and unit tested.

- [x] Ensure that all the functions which modify a fixture (E.g. [this code](https://github.com/TryGhost/Ghost/blob/a87715f68851a2937749fdfbb25e639274ae8d2b/core/server/data/fixtures/index.js#L185-L185) are idempotent (they won't have any effect if run a second time), and make sure they're all clearly named and documented.  

Inside of fixtures/index.js are a whole bunch of functions which perform data operations. These should be:

- broken out
- given better names
- checked for idempotency
- potentially unit tested

- [x] Change the [through version](https://github.com/TryGhost/Ghost/blob/a87715f68851a2937749fdfbb25e639274ae8d2b/core/server/data/fixtures/index.js#L347-L347) fixture code to be dynamic rather than hard-coded. It'd be great to just register a set of fixture migrations that have to happen at a particular version, and let those be handled without having to write extra code each time.

At the moment we have a bunch of hardcoded rules for what to do when we go 'through' a version change, which means writing a bunch of new code each time we want to migrate again. Changing this to use a convention would make lour lives much easier.

- replace hard coded rules with a simple convention for adding functions to run (in order) when we do a migration.

**Comment by ErisDS** [comment]
If anyone is interested in taking a look at one of those last three code changes which don't have a separate issue and would like some clarification, let me know and I can write up some more details rather than notes that probably only make sense to me :wink:

**Comment by kevinansfield** [comment]
> add posts.private - this is speculative, as there's high demand for certain posts being private

Would naming this `is_private` be better to avoid any conflicts with reserved keywords? If it's just `private` then anyone working with the API with certain programming languages may need to work around it.

**Comment by ErisDS** [comment]
@kevinansfield Good point well made, this is why we didn't call hashtags 'private' too...

**Comment by halfdan** [comment]
@ErisDS I'd be interested to know more about those last 3 items (first two sound most appealing)

**Comment by halfdan** [comment]
@kevinansfield @ErisDS It makes me slightly uneasy seeing `page`, `featured`, `hashtag` as booleans without the `is_` prefix and then `is_private`. I understand the reasoning - but it seems very inconsistent with the existing boolean flags. I realise it's difficult finding a fitting synonym that would work here - `secret` or `concealed` come to mind, but those aren't in line with the use of "private" in the UI. 

This might also have an impact on the theme / public API where it's going to be odd having `isPrivate` (because, consistency) and just `page` (not `isPage` nor `isFeatured`).

**Comment by ErisDS** [comment]
@halfdan The global setting for privacy is called 'isPrivate' too, so in that sense, it is consistent.

Chances are over time we'll replace page & featured with hashtags, so those fields will disappear from the DB. I understand the concern and quest for consistency, but using a synonym is just as bad in this instance, I think?

**Comment by ErisDS** [comment]
@halfdan I updated the last 3 with further descriptions.

**Comment by ErisDS** [comment]
With the naming of the field for private posts, `is_private` is consistent with the settings key for private blogs, however as pointed out, it is not consistent with other boolean fields like `page` or `featured`

Both `private` and `protected` are awkward to use because they're reserved words. Wondering if `secret` or `passworded` might be better, or whether to stick with `is_private`.

**Comment by ErisDS** [comment]
So, I have a solution to the naming problem\* here:

Normal tags are 'public', "hashtags" is a sort of "private" but not really, internal-only tags. We wanted to use private here, but it didn't feel quite right because these tags DO appear on the frontend.

The concept of a `private` post is something we want to implement in the near future, probably using the existing user system, maybe using a simple password like we do with a whole `private` blog - we're not sure yet but we know we need space in the DB to make it a reality.

Users are all public unless they're not active yet... but that might change with the ability to create special guest accounts, or deactivate a user. 

All of these concepts are annoying because the word 'private' is reserved and we want to avoid it's use n variable names/schemas, etc. All of these concepts are _actually_ a form of visibility. The logic for how it behaves is different in each model because each model performs different duties, however they're all similar in that they impact when and where an object can be seen.

So, lets do away with the booleans, and switch to having a `visibility` option on all 3 of the core models (posts, tags, users). In all 3 cases, the default will be `public`. For tags we already know we need an `internal` option, for the other two models we can leave added extra possibilities until we need them as this is just validation.

E.g:

`visibility: {type: 'string', maxlength: 150, nullable: false, defaultTo: 'public', validations: {isIn: [['public']]}},`

\* By all accounts, absolute *the* hardest problem in Computer Science.

**Comment by kevinansfield** [comment]
:+1: `visibility` field sounds good to me

**Comment by ErisDS** [comment]
Closing this for now, I think we've made all the updates that we're going to get into 0.8.0 / 005.
