### ISSUE TITLE
Sprint Epic 26th Jan - 9th Feb

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#6401]
- [ ] More work on the tour feature #5168 @acburdine 
- [ ] Adapter writeup @ErisDS

## Channels
- [x] Finishing up metadata refactoring #6186 @jtwebman
- [x] Dynamic routing for Channels PR #5091 @ErisDS

## Post Scheduling
- [ ] Finish writing issues @ErisDS
- [ ] Timezone issue :clock10: #6406 @AileenCGN 
- [ ] cron adapter #6413 @jtwebman 

## New Editor and Image Uploads
- [ ] :boom: :fire: uploader.js and refactor our image upload components @kevinansfield 
- [ ] Editor: finalize CodeMirror card to highlight additional requirements for card "apps/addons" @kevinansfield
- [ ] Editor: initial image card @kevinansfield
- [ ] Editor: look into inline-block vs block cards (eg. images could be inline so they can be mid-paragraph, vs. a fully-featured markdown editor that has to be a completely separate section) @kevinansfield

**Comment by ErisDS** [comment]
Closing in favour of #6470
