### ISSUE TITLE
Remove jquery-ui and selectize dependencies

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#6458]
We are currently bundling 2 large dependencies in the form of `jquery-ui` and `selectize`+`ember-cli-selectize`. jQuery UI is only used for drag-n-drop of the navigation items and re-ordering of tags. Selectize works well for our current use but is bloated due to needing to replicate a lot of functionality internally that Ember is much better at solving as well as needing a lot of sometimes flakey and inflexible glue code for communication and data munging between the jquery plugin and ember.

Our current and future use cases would be better served by switching to the much more lightweight and flexible `ember-power-select` + `ember-sortable` combo.

[ember-power-select](http://www.ember-power-select.com) offers very composable and flexible suite of components that work directly with Ember data structures so it will make our future plans for extending the search bar a lot easier.

TODO:
- [x] Switch navigation item drag-n-drop from `jquery-ui.sortable` to `ember-sortable` - https://github.com/TryGhost/Ghost/pull/6468
- [x] Switch `gh-search-input` from `gh-selectize` to `ember-power-select` - #6492 
- [x] Switch tags input from `gh-selectize` to `ember-power-select` - https://github.com/TryGhost/Ghost-Admin/pull/892
  - [x] Modify autocomplete on tab, create on enter behaviour (see #6912)
    - behaviour has changed slightly, both <kbd>Tab</kbd> and <kbd>Enter</kbd> will auto-complete the selected tag or create a new item if the `Add "x"...` option is selected
  - [x] Style primary tags differently to normal tags (see screenshot below)
- [x] Remove `jquery-ui` (+ additional plugins) and `selectize` dependencies - https://github.com/TryGhost/Ghost-Admin/pull/892

---

**Update 10/10/2017:** Finalisation of this has been blocked for a long time on `ember-sortable` not supporting x+y re-ordering. There is now an on-going spike at using `ember-drag-drop` instead in https://github.com/TryGhost/Ghost-Admin/pull/892.

Any solution that we end up on should allow for customisation of individual tags/tokens so that primary tags can be disambiguated:

![tag-disambiguation](https://user-images.githubusercontent.com/415/31385310-b9a5ae0a-adba-11e7-80e6-db683aafc30d.gif)
