### ISSUE TITLE
Sprint Epic 9th - 23th February

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#6470]
## Editor
- [ ] new editor demo in labs @kevinansfield

### CodeMirror card and Image Uploads
*(continuation from previous sprint)*

- [ ] :boom: :fire: uploader.js and refactor our image upload components @kevinansfield 
- [ ] Editor: finalize CodeMirror card to highlight additional requirements for card "apps/addons" @kevinansfield
- [ ] Editor: initial image card @kevinansfield
- [ ] Editor: look into inline-block vs block cards (eg. images could be inline so they can be mid-paragraph, vs. a fully-featured markdown editor that has to be a completely separate section) @kevinansfield 

## Hashtags
- [ ] finish up data version 005 #6301 @ErisDS
- [ ] hashtags in labs #6165 @ErisDS

## Channels
- [x] Wrap up tests for #6469 @ErisDS

## Post Scheduling
- [ ] Wrap up cron adapter #6413 @jtwebman 
- [ ] Publish remaining issues (once cron adapter API is tied down) @ErisDS
- [ ] Timezone issue :clock10: #6406 @AileenCGN 

## Other
- [ ] finishing up initial tour demo @acburdine 
- [ ] experimentation with validations refactor @acburdine 
- [ ] Finish adapter writeup @ErisDS

**Comment by ErisDS** [comment]
Closing in favour of #6560
