### ISSUE TITLE
Sprint Epic 23th February - 7th March

### ISSUE THREAD

**Issue by dbalders** [TryGhost/Ghost#6560]
## Editor
*(continuation from previous sprint)*
- [ ] new editor demo in labs @kevinansfield

### CodeMirror card and Image Uploads
*(continuation from previous sprint)*

- [ ] :boom: :fire: uploader.js and refactor our image upload components @kevinansfield 
- [ ] Editor: finalize CodeMirror card to highlight additional requirements for card "apps/addons" @kevinansfield
- [ ] Editor: initial image card @kevinansfield
- [ ] Editor: look into inline-block vs block cards (eg. images could be inline so they can be mid-paragraph, vs. a fully-featured markdown editor that has to be a completely separate section) @kevinansfield 

## Hashtags
*(continuation from previous sprint)*
- [ ] finish up data version 005 #6301 @ErisDS
- [ ] hashtags in labs #6165 @ErisDS 

## Post Scheduling
*(continuation from previous sprint)*
- [ ] Wrap up cron adapter #6413 @jtwebman 
- [ ] Publish remaining issues (once cron adapter API is tied down) @ErisDS
- [ ] Timezone issue :clock10: #6406 @AileenCGN 

## Other
*(continuation from previous sprint)*
- [ ] finishing up initial tour demo @acburdine 
- [ ] experimentation with validations refactor @acburdine 
- [ ] Finish adapter writeup @ErisDS

**Comment by ErisDS** [comment]
Closing in favour of #6586
