### ISSUE TITLE
Refactor private blogging into a self-contained module 

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#6589]
See the original [password protected blogs issue](https://github.com/TryGhost/Ghost/issues/4993) for some additional context.

This issue exists partly as a piece of the [frontend controller](https://github.com/TryGhost/Ghost/issues/5091) refactor because part of the handling exists there and we're trying to get rid of that file, partly as an experiment for the future of apps, and partly because there are some small improvements that can be made to the way the private blogging middleware works as well as some minor fixes.

There are a few different tasks detailed in this issue, PRs which complete

The private blogging feature allows a user to enable a shared password to be required before content becomes accessible. In future, there are a couple of things we may add to this concept: one is that we may refer to this as the "simple" version, and have an "advanced" version which uses the existing Ghost user auth to get access to posts (perhaps with a new "subscriber" user level). The second is that we may make it so that it's possible to have specific posts be private, rather than the whole blog.
## Co-locating feature code

At the moment, the code for the feature exists in several places, including:
- some [routing](https://github.com/TryGhost/Ghost/blob/master/core/server/routes/frontend.js#L28)
- the [frontend controller](https://github.com/TryGhost/Ghost/blob/master/core/server/controllers/frontend/index.js#L147)
- lots of [middleware](https://github.com/TryGhost/Ghost/blob/master/core/server/middleware/private-blogging.js)
- a [template](https://github.com/TryGhost/Ghost/blob/bf0e40eda12bc5af9a59856fff78d76a97b39e07/core/server/views/private.hbs)

This feature is a great candidate for being (and was always intended to be) moved to an app (auto-installed for those who are using it). It has some routing, a controller, some middleware and a template. It performs quite complex logic, and iirc even has a dependency, all of which is only needed if the feature is enabled. Experimenting with refactoring this will give us some idea of the kind of extension points we need in order to make apps a reality.

In the short term, the idea is to move all the code which handles private blogging into a single place, such as (up for discussion) `/core/server/apps/private-blogging/` - the idea being to move some of our lesser-used features into internal apps short term whilst we figure out how that should work. 

We categorically don't have the hooks right now to make this work 100%, but starting to move the code should identify what hooks are needed and give us a place to start the discussion on what they should look like. Where it's relatively straightforward, hacky versions of hooks/filters/apis can be used for now, provided they're documented here or in another open ticket as something that needs to be worked on :wink: 

Note: if you start working on this, please also consider the tests - they should be moved to be a single set of tests in a single file as well, IMO. The thought is, if we did move this into an external app, the tests would go with it :smile: 
## Middleware optimisations

The middleware, which is located [here](https://github.com/TryGhost/Ghost/blob/master/core/server/middleware/private-blogging.js#L48) and enabled [here](https://github.com/TryGhost/Ghost/blob/master/core/server/middleware/index.js#L113) is currently always there, but only does something if the private blogging feature is enabled. This could be refactored so that the middleware is only enabled if the feature is enabled - by moving the check back a level we can be sure to only ever do 1 check. From the perspective of extension points (like our existing filter mechanism, and the helpers for handlebars) there could be a concept of "registering" middleware, which inverts control and ensures the middleware is only "registered" if it needs to be. 
## Hardcoded strings

In a couple of places, `/private/` is being used as a hardcoded string. E.g. https://github.com/TryGhost/Ghost/blob/master/core/server/middleware/private-blogging.js#L48

However, this should be using the `config.routeKeywords.private` value: https://github.com/TryGhost/Ghost/blob/master/core/server/routes/frontend.js#L45. It's not a problem right now, but if we gave users the ability to change the route keywords, this would result in a bug.
## Configuration clashes

At the moment, it is possible to end up with a configuration clash - if you install Ghost in a subdirectory called "private", and then enable private blogging, which has a page that lives at `/private/`, then bad things happen as documented in https://github.com/TryGhost/Ghost/issues/5914. This is an edgecase, and although there is a [PR with a suggested fix](https://github.com/TryGhost/Ghost/pull/5922), I'm not 100% sure the fix won't just give us more common problems.

Perhaps a better approach (as suggested in #5914) is just to output an error/warning message if the subdirectory & config.routeKeywords.private (or any routeKeyword) matches. Afterall, routes like `/private/private/` are weird even if they aren't wrong.
# Tasks
- [x] Move as much of the code to be co-located as possible (should also co-locate tests)
- [ ] Work on adding proper hooks, rather than hacky ones (should probably be a separte issue)
- [ ] Optimise private blogging middleware, so it is only enabled if private blogging is enabled
- [x] Ensure there are no hardcoded "private" strings
- [x] Display an error message if the private string & subdir string match

**Comment by nuclearpengy** [comment]
:+1: Exciting! :)

**Comment by acburdine** [comment]
I've started some work on this. @ErisDS should I go ahead and try experimenting with adding some hooks?

**Comment by acburdine** [comment]
The two hooks that are needed (at least for the private blog one) is a hook in the middleware layer and the hook in the routing layer. Those two hooks are called in the same function, but just at different times.

**Comment by ErisDS** [comment]
I've updated the task list on this to try to make it a little bit clearer what is the expected outcome from co-locating the code. I 100% understand we don't have the tools right now to make this fully separated, but by a 'hacky hook' what I meant was (in the first instance) something like this in the routing layer:

```
// @TODO: figure out how to do this properly
require('./new/path/to/private-blogging').setupRoutes();
```

That's all I was thinking of for step 1 - move the code, add hacky todos, and then document them all. With all that done, separate issue(s) can be raised to figure out how to architect the hooks/filters/extension points once we have a clear picture where they are and what we need to pass around.

**Comment by acburdine** [comment]
Quick comment/question on the middleware optimization: the second private blogging middleware function immediately exits if the blog isn't private by calling the `next()` method. How much overhead is there per middleware function?

I remember when I built the original feature I had to split the functionality into two separate functions because of the way the `cookie-session` has to be set up. I'm wondering if it wouldn't be better to leave it as it is?

**Comment by ErisDS** [comment]
@acburdine the optimisation task is separate to the refactor task, because I think the refactor makes the optimisation task easier / clearer. 

I think we can move towards making it so that all of the private blogging routes and middleware only get added / setup if the checkbox in the admin panel is set. 

The settings in the admin panel are going to be, for now, not part of the 'app' as it were, because we don't yet have any clarity at all around how UIs for apps will work.

**Comment by ErisDS** [comment]
Going to close this. Private blogging _is_ effectively its own module now. Any improvements we make to the general internal app framework which improve how it work will probably be done for all of our internal apps and we'll likely forget to tag this issue anyway 😁
