### ISSUE TITLE
Refactor & improve reliability of "secure" handling for urls

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#6593]
This has been bugging me for ages! Our handling of whether or not a request is secure, and also whether or not a URL or URI should be output with http, https, or schema-less, isn't very robust. It's an aspect of Ghost that frequently runs into bugs, regressions and edge-cases.

Some time ago, a [concerted effort](https://github.com/TryGhost/Ghost/issues/1833) was made to bring all of the URL creation code into a single location, and so [urlFor](https://github.com/TryGhost/Ghost/blob/master/core/server/config/url.js#L149) was born and used throughout the app. Having the code co-located makes it much easier to reason about and has reduced the number of issues with subdirectories getting forgotten about, but we're still not quite there in terms of whether a request is secure. Some [recent further work](https://github.com/TryGhost/Ghost/pull/6297) has improved the situation, but we're still not quite there yet.
## Underlying problem

The underlying issue here is that the proper way to detect whether a request is secure is to look up `req.secure`, where req is the express request object handed to the middleware. In Ghost, by the time we come to ask for a URL, we are usually outside of the middleware flow (or have lost our reference to `req`) so we can no longer check `req.secure`. However, in most cases, we are still inside the handlebars / theme / helper system, and here we ALWAYS know whether or not the given request was secure because Ghost passes `req.secure` to `res.locals.secure` [here](https://github.com/TryGhost/Ghost/blob/master/core/server/middleware/theme-handler.js#L49). 

Therefore, if we're in a handlebars helper, the setting is always available through `options.data.root.secure`. To explain, in the [url helper](https://github.com/TryGhost/Ghost/blob/master/core/server/helpers/url.js#L10), we get `absolute` from `options.hash.absolute`, and we can just as easily get `secure` from `options.data.root.secure` and pass this to the `urlFor` function. I think the main reason for the problem we have, is that this fact about how to get the `secure` flag wasn't known when the code was written. 

So, instead of looking up whether we're in a secure request, and passing this information to `urlFor`, at the moment, we set the `secure` flag on the data that we're sending to the frontend. Worse, if that data is, for example, an entire list of posts, we set it on each post!!! See these two snippets:
- https://github.com/TryGhost/Ghost/blob/master/core/server/controllers/frontend/render-channel.js#L31
- https://github.com/TryGhost/Ghost/blob/master/core/server/controllers/frontend/index.js#L121

This is horrible! And totally unnecessary - when the url helper gets called, it already has this information and could easily do the work of passing the secure flag to `urlFor`.
## Considerations for refactoring

The blocker to starting this refactor, at the moment, is that if you delete the two pieces of code that call `setRequestIsSecure`, and run the tests, they all pass still! There's absolutely no coverage of this usage... where a URL is generated inside a theme template for a secure request.

So, first things first, we need to write a test that fails when `setRequestIsSecure` is removed.

Once that is done, we can remove `setRequestIsSecure`, in favour of passing the secure flag from the helper. How this is done, needs a little thought and perhaps some trial and error. We probably need to change the method signature for `urlFor`, however it's probably worth using the existing way of setting it on data, adding tests, and then taking a look at the bigger picture of url generation.

Doing a search in the codebase for `urlFor` should turn up just over 100 usages of the function, although many are tests (not enough though, apparently!). Looking at all the different usages should start to show a pattern of the different types of URLs we need to build, and it should be easy to spot additional ugly ways of passing `secure` by setting it on data, e.g. [here](https://github.com/TryGhost/Ghost/blob/1f4c01d207618f39b908c969a9875a4de1b92f53/core/server/data/meta/previous_url.js#L12-L12).

As discussed in [this issue](https://github.com/TryGhost/Ghost/issues/6270), what should start to become clear here, is that there are different types of absolute urls that we may need to create:
- **protocol-relative absolute URLs** - need to use the protocol of the request, so if the request is secure, the generated URL should be https.
- **default / canonical absolute URLs** - need to use the blog's default protocol. E.g. if `config.url` is http, then the URL should be http, regardless of the request.
- **schema-less absolute URLs** - we haven't got an example of doing this, but it may in some cases be better to ask for a url without a schema/protocol, as a simpler way to create protocol-relative URLs - particularly for images.

There is likely quite a lot which can be done to improve the `urlFor` code and it's helper methods, to come up with a smart way to determine what the default base schema/url is for the blog based on the config, and to be able to instruct `urlFor` to build the absolute url that we need at a given moment.
## Tasks
- [ ] Write tests that fail if `setRequestIsSecure` is removed from the frontend controller code
- [ ] Remove `setRequestIsSecure` in favour of passing the secure flag from the helper options
- [ ] Refactor urlFor to have a smarter method signature, and update all the usages

**Comment by ErisDS** [comment]
Closing this now in favour of #9192, refactoring how urls are created should allow this to happen naturally.
