### ISSUE TITLE
Sprint Epic 22nd Mar - 5th April

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#6627]
@acburdine 
- [ ] Finish the ember-power-select switchover (#6492/#6587)
- [ ] Finish the private blogging module refactor (#6589/#6617)
- [ ] Finish the initial tour wiring (#6358)
- [ ] Experimental inline-validations refactor (#6647)

@AileenCGN 
- [ ] First pass at slack integration #6584 

@erisds
- Write must-have migrations for data v005 #6301 
   - [x] remove `hidden` from tags
   - [x] add `visibility` to users, tags and posts
   - [x] add `mobiledoc` field to posts
   - [x] add `facebook` & `twitter` fields to users
   - [x] update client admin fixture 
  -  [ ] add client api permissions fixtures
- [ ] Update 'hashtags' code to work with new `visibility` column
- [ ] Do a release (either 0.7.9 if pre 005, or 0.8.0 if post 005). Note that there is now a [milestone for 0.8.0](https://github.com/TryGhost/Ghost/milestones/0.8.0)

@kevinansfield 
- [x] :boom: :fire: uploader.js and refactor our image upload components
- [x] Editor: bring up to date with latest mobiledoc changes
- [ ] Editor: finalize CodeMirror card to highlight additional requirements for card "apps/addons" 
- [ ] Editor: initial image card 

@sebgie 
- [ ] rework data structure of tokens for v005 #6626
- [ ] check if ESA can handle new refresh tokens #5202

**Comment by ErisDS** [comment]
Closing as we're working on different projects in a slightly different format. We may come back to using sprint epics in the future.
