### ISSUE TITLE
Sprint Epic 6th - 19th April

### ISSUE THREAD

**Issue by dbalders** [TryGhost/Ghost#6678]
@acburdine 
- [ ] Finish the initial tour wiring #6358
- [ ] Experimental inline-validations refactor #6647
- [ ] Finish up the clients api #6674

@AileenCGN 
- [ ] First pass at slack integration #6584 

@erisds
- Write must-have migrations for data v005 #6301 
  -  [ ] add client api permissions fixtures
- [ ] Do a 0.7.9 release. Note that there is now a [milestone for 0.8.0](https://github.com/TryGhost/Ghost/milestones/0.8.0)
- [ ] Look at unpicking the ghost-showdown mess

@kevinansfield 
* New mobiledoc based editor #6255
  - [ ] finalize CodeMirror card to highlight additional requirements for card "apps/addons" 
  - [ ] spike image handling (atoms vs cards, inline vs block, etc)
  - [ ] improvements to the card insert/editing experience
  - [ ] stretch goal: look at alternative toolbar options

@sebgie 
- [ ] rework data structure of tokens for v005 #6626
- [ ] check if ESA can handle new refresh tokens #5202

**Comment by ErisDS** [comment]
Closing as we're working on different projects in a slightly different format. We may come back to using sprint epics in the future.
