### ISSUE TITLE
Data Model: Overhaul

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#7432]
Shipping Ghost 1.0 without having to worry about backwards compatibility\* gives us the perfect opportunity to overhaul and improve the data model we have in Ghost.

There are numerous changes that we want to make, all of them have or will have their own sub issues. As well as changing the underlying data model, we're also going to be resetting and upgrading our database migration system, to try to make it easier to make changes in future versions.
### Alpha 1 / master

In the master branch (alpha.1) we have disabled migrations and made Ghost refuse to start if your `databaseVersion` number in your settings table doesn't match `/^alpha/`. This is pretty hardcore and was done to prevent anyone incorrectly running a real live production blog using the `master` branch from accidentally starting alpha Ghost with data they care about.

For developers, working around this is pretty simple for now, you need to change the value of your `databaseVersion` and Ghost will start. Obviously, as we make more changes to the underlying schema, it will become required for you to delete your database and let Ghost recreate it fresh. For the time being, the import/export tools may just about work if you need to get some test post data into your blog. 
### Desired changes

These will all get issues if they haven't already
- [x] Switch to using utf8mb4 encoding ⭐️⭐️⭐️
- [x] Remove all auto-increment keys in favour of ObjectId ⭐️⭐️⭐️
- [x] Audit the text field types and lengths (hard limits) #4134 ⭐️⭐️⭐️
- [x] create issue for soft limits #4134, see 8143 ⭐️⭐️
- [x] Image related changes: ⭐️⭐️
  - [x] Fix the inconsistent naming of image fields across the resources
  - [x] Review the need for image sizes
  - [x] Consider adding additional image fields to each resource
  - [x] Consider adding an image table
- [x] Split invites out from the users table ⭐️⭐️
- [x] Rework the invites roles table into a field on the invites table ⭐️
- ~~[ ] Consider refactoring the tokens table: #6626 ⭐️~~
- [x] Handling of identities vs users for the new Ghost OAuth login system ❓
- ~~Split pages out from the posts table ⁉️~~
- ~~Revisit unique constraint on tags: #4687 ❓~~
- ~~[ ] Change `last_login` in users to `last_seen` and revisit how it works with Ghost Auth vs password auth? ❓(see #8258)~~
- ~~Maybe add custom fields to main resources (do this later)~~

\* _No backwards compatibility means that, unlike all previous versions of Ghost, there won't be a built in migration path. There **will** be a way to migrate data from one to the other, however we won't settle on what that tool is going to look like until we've decisions on the exact changes we're making_ 😉

**Comment by kirrg001** [comment]
>  create issue for soft limits #4134, see 8143 ⭐️⭐️

I have added a separate issue for soft limits and added it to the backlog.

> Consider refactoring the tokens table: #6626 ⭐️

I would delete this sub task from this issue and put the original issue into the sprint. I decided against the backlog, because if 1.0.0 is in beta, we have to add a migration script?
We have a centralised place to create tokens now, it will be easy to add. 
Otherwise we can't delete related refresh tokens for the issue which was raised here https://github.com/TryGhost/Ghost/issues/6384.


> Handling of identities vs users for the new Ghost OAuth login system ❓

I would delete this sub task, because i am not sure what we would like to achieve here.

> Split pages out from the posts table ⁉️

Would be nice, because it would make the code cleaner, but i am afraid it will complicate the database queries. Because you never know if an incoming request for a url is a page or a post. So you have to query to collections?Same for fetching all posts and pages. I assume this sub task is bigger then we think.

> Revisit unique constraint on tags: #4687 ❓

I would delete this sub task, because first it hasn't made any trouble in the past and second the slug is unique.

> Change last_login in users to last_seen and revisit how it works with Ghost Auth vs password auth? ❓

I would delete this sub task, because i am not sure what we would like to achieve here. With Ghost Auth strategy the user exchanges an auth code via Ghost when signing in and then a pair of local tokens are created. `last_login` property is set when a new token is added. So this is still valid for both cases in my opinion.

> Maybe add custom fields to main resources (do this later)

I would delete this sub task, because i am not sure what we would like to achieve here.


@ErisDS If you have any concerns or if you disagree with any of my reasonings, let me know here 👍

**Comment by kirrg001** [comment]
@ErisDS ping 🙃

**Comment by ErisDS** [comment]
>> Consider refactoring the tokens table: #6626 ⭐️

> I would delete this sub task from this issue and put the original issue into the sprint. I decided against the backlog, because if 1.0.0 is in beta, we have to add a migration script?
We have a centralised place to create tokens now, it will be easy to add.
Otherwise we can't delete related refresh tokens for the issue which was raised here #6384.

Is this required for the beta or no? If we have to have it then this will need raising as a separate issue and adding in I guess.

>> Handling of identities vs users for the new Ghost OAuth login system ❓

> I would delete this sub task, because i am not sure what we would like to achieve here.

I think this needs checking off rather than deleting, we have all the handling in place for coping with users that live in GhostAuth now, with the exception of the slug bug which is raised and in the milestone.

>> Split pages out from the posts table ⁉️

> Would be nice, because it would make the code cleaner, but i am afraid it will complicate the database queries. Because you never know if an incoming request for a url is a page or a post. So you have to query 2 collections?Same for fetching all posts and pages. I assume this sub task is bigger then we think.

Yes, I have gone back and forth on this several times. I agree we should leave it for now. 

>> Revisit unique constraint on tags: #4687 ❓

> I would delete this sub task, because first it hasn't made any trouble in the past and second the slug is unique.

Agree 👍 

>> Change last_login in users to last_seen and revisit how it works with Ghost Auth vs password auth? ❓

> I would delete this sub task, because i am not sure what we would like to achieve here. With Ghost Auth strategy the user exchanges an auth code via Ghost when signing in and then a pair of local tokens are created. last_login property is set when a new token is added. So this is still valid for both cases in my opinion.

The `last_login` field in the DB is used to store a timestamp whenever a [new token is added](https://github.com/TryGhost/Ghost/blob/c9f551eb9648e756f3ac0c5ce49e257a7ac7b85b/core/server/models/base/listeners.js#L13-L13) and is used to show a "last seen" field:

![](https://puu.sh/v801I.png)

This sub task was to do two things:

1. rename the field to `last_seen` because it does not represent the last time the user physically logged in (e.g. entered their password) and is confusing
2. to check if this behaviour still works in a reasonable way in Ghost 1.0 with GhostAuth.

I think these 2 tasks are small and worth doing?

>> Maybe add custom fields to main resources (do this later)

> I would delete this sub task, because i am not sure what we would like to achieve here.

Yes can delete this for now. The idea is to add a set of custom fields to posts, tags and users e.g. `custom_field_key_1`, `custom_field_value_1`, `custom_field_key_2` `custom_field_value_2` - as a way for publications to define an extra field or two on those key objects. It was an idea that was not really very well thought through and not something we want to do at this late stage. Maybe a labs feature for Ghost 1.1 😄

**Comment by kirrg001** [comment]
> Is this required for the beta or no? If we have to have it then this will need raising as a separate issue and adding in I guess.

Yeah i would add it for the beta. I wouldn't merge the tokens into one table, we can just add a `issued_by` property to the access token table. By this we can easily know which access token was issued by which refresh token. Example: you change your password and you would like to delete all access tokens from this user (except of the current) + the related refresh tokens. I don't think we have to raise a new issue, we can use #6626.

> rename the field to last_seen because it does not represent the last time the user physically logged in (e.g. entered their password) and is confusing
to check if this behaviour still works in a reasonable way in Ghost 1.0 with GhostAuth.

👍

**Comment by kirrg001** [comment]
Closing. I have raised a separate issue for the `last_login` property. This and #6626 were added to the beta milestone.
