### ISSUE TITLE
Theme API Audit

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#7491]
I'm currently working through, reviewing all the open (and many closed) issues & PRs with the `themes` label. In doing this, I'm collecting together a set of quick wins & bigger changes I want to make as part of the alpha process.

This should feed into a set of subtasks/issues, and ultimately into a blog post about what's changing. 
- [x] review open issues w/ theme label

Known things which need extended reviews:
- [ ] asset helper + envs
- [ ] excerpts?
- [x] deprecations

Other tasks:
- [ ] write up the new package.json spec
- [ ] create a validator for the new package.json spec in gscan
- [ ] write a blog post about all the changes

The plan is that, with the exception of features that have been deprecated for over a year, like some of the body classes and `page_url`,  although some changes may be required for a theme to work with Ghost 1.0.0, themes that work with 1.0.0 should also work on the 0.11 LTS branch. E.g, themes can be prepared in advance of the release of Ghost 1.0.0.
- [x] Remove the deprecated features
- [x] Get rid of validateActiveTheme
- [x] scan themes with gscan when copied themes manual to themes folder (we could scan the active theme on the first http request to ensure it's 100% valid or similar ideas)

Error handling:
- [ ] Revisit stack printing
- [x] Simplify logic for finding the error template
- [x] https://github.com/TryGhost/Ghost/issues/6894#issuecomment-221700724
- [x] Split templates for error rendering in themes (see comment [here](https://github.com/TryGhost/Ghost/issues/6894#issuecomment-221700724)

**Comment by kirrg001** [comment]
Some things in this issue are a little unclear to me, but let me write down tasks and questions.
This comment can contain misinterpreted facts - can be corrected/updated. 

Questions:
1. remove deprecations is marked as finished - when and how was this done?
2. should we require a package.json for 1.0 themes?We could release a gscan 1.0, which contains this breaking change. LTS need's to use the 0.X gscan version. But a 1.0 theme can be still used in an LTS version.

Required Tasks:
- [ ] excerpt: https://github.com/TryGhost/Ghost/issues/5060 - i need help with this for sure: what is the state, there are open PR's and lot's of comments. We can discuss via DM to bring me up-to-date with this and then i will update this TODO
- [ ] finish packagejson documentation https://themes.ghost.org/v1.0.0/docs/packagejson
- [ ] add packagejson validation (see comment https://github.com/TryGhost/gscan/issues/15#issuecomment-242033448)
- [ ] scan themes with gscan when copied themes manual to themes folder (we could scan the active theme on the first http request to ensure it's 100% valid or similar ideas) - security task

Optional Tasks:
- [ ] Revisit stack printing (https://github.com/TryGhost/Ghost/blob/master/core/server/middleware/error-handler.js#L21)
- [ ] improve the asset helper https://github.com/TryGhost/gscan/issues/32
- [ ] error-404.hbs and error-500.hbs (https://github.com/TryGhost/Ghost/issues/6894#issuecomment-221700724)

**Comment by ErisDS** [comment]
The work for this issue expanded a bit, because all of the code that currently makes themes work is split across config & settings in awkward ways. It was time to solve these problems so that we can move forward cleanly.

- [ ] Move the settings cache out of the settings API #8057, fixes #8037
- [x] Use a GET /themes/ endpoint for the theme list 
- [ ] Remove availableThemes from BOTH settings & config (PR coming when #8057 is merged)
- [ ] Change theme loading to NOT load all files (LTS + alpha, fix #8056, PR coming today)
- [ ] Separate out asset helper for admin & themes (fixes #7958)

Two other new items:

- [ ] New concept of "theme config", move posts per page setting there (new issue coming)
- [ ] Change get helper as described in #7242

**Comment by ErisDS** [comment]
I have an open PR for everything now except for

- [ ] Change get helper as described in #7242
- [ ] Remove content=0 hack

As I forgot about these 😞 they are small at least.

All the stuff to do with the package.json spec & gscan will be part of the migration path work I think?

I am not sure what "Revisit stack printing" was?

- All the stuff to do with excerpts was not scheduled for 1.0

I would also have liked to have made more progress with the asset helper, at least we have a plan for not sharing it between themes and admin again. More improvements can come in future without breaking changes, I think.

**Comment by ErisDS** [comment]
Further update - this is mostly as done as it will be for 1.0. Some cleanup work to do around the asset helper now that the admin-server split is done and lots of documentation to do along with updates to gscan.

**Comment by kirrg001** [comment]
@ErisDS Could we raise one or two separate issues with the missing pieces and close this big issue?
Let me know 👍

**Comment by ErisDS** [comment]
Have raised #8219, #8221 & #8222 to capture what's left here.
