### ISSUE TITLE
Overhaul of content screen layout

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#7860]
## Main changes:
- removal of preview pane instead having a single list of posts
- addition of basic filters
  - All
  - Published
  - Scheduled
  - Drafts
  - Pages?
- improvements to infinite scroll

### Stretch goals:
- advanced filter (filter by title, tag, etc)

## Progress

- all functional changes are in place, only [final styling of filters](https://github.com/TryGhost/Ghost/issues/8021) remains

*TODO*

- [x] investigate loading performance issue
  - the occasional delay when scrolling appears to be a rendering issue rather than slow API responses
  - Glimmer 2 may improve things automatically
- [x] keyboard navigation?
  - up/down highlights post
  - enter key opens post in editor
  - cmd-delete triggers delete post modal
  - left/right switches filters?
- [x] dropdown filters for type, author, tag
- [x] dropdown selector for order
- [ ] styling (in-progress, see https://github.com/TryGhost/Ghost/issues/8021)

## Related issues:
- [x] Bug: Content management items #6006
  - no need to load next post after deletion as there's no longer a preview pane
- [x] Filter content list by tag #6190
- [x] Unable to directly load a post that's not in the first page #6215
  - there's no longer a preview so any links directly to a post should load that post in the editor
- [x] Deprecations thrown when content screen changes from mobile<->desktop #6398
  - we no longer watch media queries as there's no need to switch between single and double panes
- [x] Make post edit button static #7210
  - there's no longer an edit post button
