### ISSUE TITLE
Ember Concurrency refactor

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#7865]
### Issue Summary

We currently have two spinner buttons:

- `gh-spin-button` - handles promises
- `gh-task-button` - handles ember-concurrency-tasks

In order to implement https://github.com/TryGhost/Ghost/issues/7515 both spinner button components will need to be updated to handle differing styles and behaviours between promises and tasks. I think this is a good time to standardise on one or the other, `ember-concurrency` gives us a few benefits over promises, especially as tasks can be linked to buttons and be triggered externally (e.g., via keyboard shortcut or other trigger outside of the button components scope) without jumping through lots of hoops to observe promise state.

### TODOs

- [x] decouple task button from spin button (https://github.com/TryGhost/Ghost-Admin/issues/496)
- [x] move all existing buttons over to ember-concurrency (minimum needed to drop gh-spin-button)
  - [x] modals (https://github.com/TryGhost/Ghost-Admin/issues/496)
  - [x] settings (https://github.com/TryGhost/Ghost-Admin/pull/569)
  - [x] editor (https://github.com/TryGhost/Ghost-Admin/pull/588)
  - [x] reset password flow (https://github.com/TryGhost/Ghost-Admin/pull/502)
  - [x] signin (https://github.com/TryGhost/Ghost-Admin/pull/571)
  - [x] signup (https://github.com/TryGhost/Ghost-Admin/pull/643)
  - [x] setup (https://github.com/TryGhost/Ghost-Admin/pull/644)
- [ ] remove `gh-spin-button` component
- [ ] improve other internal uses of promises by leveraging ember-concurrency

**Comment by kevinansfield** [comment]
In most cases creating ember-concurrency tasks so that we can use `gh-task-button` in place of `gh-spin-button` is fairly straightforward (see https://github.com/TryGhost/Ghost-Admin/pull/496 for examples), if anyone feels like picking up any of the remaining uses of `gh-spin-button` please comment here with which instances you are tackling, thanks 😄

I'll update the todo list with a name next to any in-progress items.

**Comment by acburdine** [comment]
Some of these (esp. settings) I'm doing as part of the validations refactor.

**Comment by kevinansfield** [comment]
@acburdine cool, if there are any specific ones you are working on would you mind updating the issue and putting your name next to them? If would be good if we can have both refactors on-going in parallel so that one is not dependent on the other.

**Comment by ErikCH** [comment]
Are you still looking for help on this? First time contributor here. I was looking at the signup.hbs and I saw only two instances of the gh-spin-button component. One on the  authenticateWithGhostOrg action that's in the route and the other is the signup action in the controller.

I suppose the same refactor you did in the signin controller could be done here. I could move the authenticateWithGhostOrg from the signup route back into the controller since I think tasks can't be used in routes. Then update the actions into Ember concurrency tasks. I'm not really sure who's calling the authenticate action in the signup route though, or if that should be moved to the controller.

**Comment by ErikCH** [comment]
@kevinansfield What do you think?

**Comment by acburdine** [comment]
@ErikCH I'd say if you're still up for it then the help would be appreciated 😄

**Comment by ErikCH** [comment]
@acburdine Good meeting you at Emberconf! I'll work on signup. I'll move the authenticateWithGhostOrg method into the controller, update the ember concurrency tasks and see what you guys think.

**Comment by ErikCH** [comment]
Looks like you guys already have a handle on setup and signin. Maybe, I'll try to catch the next one.

**Comment by kevinansfield** [comment]
Hey @ericschultz 👋 Sorry about that, your messages must have got lost in my GitHub notification noise 😞 This issue was part of our 1.0-beta push so had deadlines attached to it.

Keep an eye on GitHub, we're always happy for contributions if anything takes your fancy! If you don't get a response on here straight away pop into the #core-dev channel on our [Slack team](https://slack.ghost.org) 😄
