### ISSUE TITLE
Ghost 1.0 UI

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Ghost#8021]
Keepin' track of 1.0 UI things

- [x] Update application UI frame
- [x] New content management UI
- [x] Update button styles
- [x] Update modal styles
- [x] Update subscribers styles
- [x] Consolidate team/apps UI components
- [x] Rename team/apps UI component
- [x] Update labs styles
- [x] Update general settings styles
- [x] New editor UI
- [x] New editor publish button workflow
- [x] New tags UI
- [x] New edit profile UI
- [x] Night shift
- [x] Wire up night shift option in labs to load app-dark.css instead of app-css - @acburdine ?
- [x] Polish
- [x] New mobile navbar
- [x] Fix mobile nav toggle - @acburdine ?
- [x] New design screen w/ update theme mgmt
- [x] Content filter dropdowns

**Comment by ErisDS** [comment]
Any thoughts on moving the themes table + maybe supporting some of the new stuff we should get from the updated package.json specs?

**Comment by JohnONolan** [comment]
Moving themes table, I think so yes, I need to do settings/general first to kind of figure out how that's going to work to have an idea of where it might go. But yes, def thinking about it!

**Comment by ErisDS** [comment]
Finished 🎉 ✨
