### ISSUE TITLE
Alternative sign in path if remote authentication fails

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#8101]
We would like to offer an alternative sign in approach.

### Requirement

Blog uses remote authentication (OAuth).

### Problem
The remote authentication service could be down or people can't login and suffer from a bug.

### Possible solution
We offer an alternative sign in via email only (password less). This can be realised by sending a mail to the user containing a one time token.

### Open research/decision
If we return a very short token, Ghost-Admin need's to find a way to handle this case.
It's in discussion if we return a short token and force the user to re-login if the remote service is available again or if we return a long time token in the user can just proceed.

### TODO's (in progress)
- [ ] decide for a solution
- [ ] add route to send a token per email
- [ ] show alternative button if user can't login right now @kevinansfield 
- [ ] handle token handling @kevinansfield
