### ISSUE TITLE
Migration path from LTS to 1.0

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#8141]
We will introduce a migration path from LTS to 1.0 soon 🐩
To realise this, we need to keep track of some tasks, which need to be done.
The goal is to be able to import a LTS export into a 1.0 blog.

#### TODO
- [x] if we don't use the database importer/exporter, we have to take care of the database encoding, see https://github.com/TryGhost/Ghost/issues/5945#issuecomment-274156796
- [x] see comment #7932#issuecomment-280674091: make the importer tests better. especially for the cases where we have changed database contraints in 1.0
- [x] import post content (transform into mobiledoc markdown card?)
- [x] go over the schema changes and transform the old attributes into the new (e.g. legacy settings)
- [x] #8437 `en_US` setting to `en` (default_lang -> lang)
- [x] an active theme import is never supported - we have to show a warning that the active theme was not imported - the user has to upload the theme again

**Comment by pascalandy** [comment]
Following this :)

**Comment by kirrg001** [comment]
Closed via #8498
