### ISSUE TITLE
Amperize issues

### ISSUE THREAD

**Issue by AileenCGN** [TryGhost/Ghost#9022]
### Issue Summary

We detected three major problems within the [Amperize](https://github.com/jbhannah/amperize) repository:

1. **Images without extension**
Images like this https://www.zomato.com/logo/18163505/minilogo work, but don't have an extension and will therefore cause an error in the underlying `image-size` library. 

2. **One image fails all**
If one image fails to load, none are loaded. This is simple to test by adding an image (open amp page) then add another image with a made up name and view the amp page again. Both images are missing. 

3. **Redirects are not followed**
Redirected image URLs are not followed. Within Ghost (where we use a similar logic to fetch image dimension), we fixed this by changing to `got` for our requests. See https://github.com/TryGhost/Ghost/pull/8953 and the follow up PR https://github.com/TryGhost/Ghost/pull/8980.

### Todos/Sub-issues
- [x] Images without extension: https://github.com/jbhannah/amperize/issues/97
- [x] One image fails it all: https://github.com/jbhannah/amperize/issues/98
- [x] Redirects are not followed: https://github.com/jbhannah/amperize/issues/99 -> https://github.com/jbhannah/amperize/pull/101
- [x] ✋ Waiting for reply of repository owner about further maintaining. This will decide, if we'll start forking and use the fork as dependency, or continue with the original repository (but with possible merge rights)

_Note: I created a new repository which is fixed the above mentioned issues. It is possible to either port those changes to the Amperize repository, my fork of it, or using the new repository. All dependent on how the repository owner plans to keep maintaining it or not._

**Comment by kirrg001** [comment]
@AileenCGN 

> Images without extension: jbhannah/amperize#97

Is that a hard thing to fix? Otherwise, assign a PR to me in amperize and then we can close this issue 👻
