### ISSUE TITLE
Refactoring: API/Model layer - pass options object

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Ghost#9127]
## Problem description

There are two problems.

### API layer and pipeline
If you take a look at this [commit](https://github.com/TryGhost/Ghost/commit/1e2beface1a1caaeb2b727e23adaa7a7e1b09042), you will see that the way our [pipeline](https://github.com/TryGhost/Ghost/blob/master/core/server/utils/pipeline.js) tooling works, clashes with how our API layer works. The API layer always needs access to the modified options object. These modifications happen in stages e.g. permissions are getting added. Furthermore, the pipeline tooling requires us to return the options in each function call, [see](https://github.com/TryGhost/Ghost/blob/master/core/server/api/authentication.js#L251).
Furthermore, it's a mixed design, because we pass an argument by reference, we modify it, but we have to return it. That is super confusing. Either you get an argument, you create your own object, eat from the argument and return the new object or you follow the pattern of object modification. 

```
  something(options) { 
    options.a = 'lol';
    returns options; 
  }
  
  beautiful(options) { 
     assert.true(options.a); 
     returns options; 
  }
  
   pipeline([something, beautiful], options)
 ```

### Model layer and the access plugin
The model layer uses two different techniques to determine the permissions of a model query. The [access rules plugin](https://github.com/TryGhost/Ghost/blob/master/core/server/models/plugins/access-rules.js) and the [direct check](https://github.com/TryGhost/Ghost/blob/master/core/server/models/user.js#L202). The access plugin requires us to pass the permission context into the `.forge` function, which instantiates a new model. Doing that allows us to use a helper function like [`isPublicContext`](https://github.com/TryGhost/Ghost/blob/master/core/server/models/post.js#L546). Right now, it's almost never used and we have permission checks in the whole system, not just in the model layer. Plus bookshelf follows the concept of the options pattern very strong. You always have to pass your options into function calls e.g. `.fetch(options)`. The outcome of this is that on each model hook we are able to access our options. So having access to [this._context](https://github.com/TryGhost/Ghost/blob/master/core/server/models/plugins/access-rules.js#L41), is not useful, because we can access the options anyway in each function. 

## This is how the options object get's passed through the system
- options object is created in our [API HTTP wrapper](https://github.com/TryGhost/Ghost/blob/master/core/server/api/index.js#L248)
- [passed into API](https://github.com/TryGhost/Ghost/blob/master/core/server/api/index.js#L264) and [see](https://github.com/TryGhost/Ghost/blob/master/core/server/api/posts.js#L39)
- [request body get's added if available](https://github.com/TryGhost/Ghost/blob/master/core/server/api/utils.js#L70)
- [permissions are added](https://github.com/TryGhost/Ghost/blob/master/core/server/permissions/parse-context.js)
- [forwarded to model](https://github.com/TryGhost/Ghost/blob/master/core/server/api/posts.js#L58)

## Questions
What is the best way to pass it around?
How to keep track of the API options object?
Get rid of .forge?

### Replace pipeline in the API layer
This requires us to make even more usage of the options pattern.

```
  permissions(options) { 
    options.context = {...};
  }
  
  query(options) { 
     models.Post.edit(options)
       .then(function(updatedModel) {
           options.response = updatedModel;
       });
  }
  
  pipeline([something, beautiful], options)
       .then(function(options) {
  });
 ```

The full options object would look like this:

```
{
  context/permissions: {},
  data: {},
  params: {},
  response: {},
  transacting: {}
}
```

### Remove the access plugin
Remove the plugin for now and use direct context checks. The future goal here is to make the context object very powerful e.g. by creating a class e.g. `new Context()`, which is passes within the options object, which then allows you to call `options.context.isPublic()`.

## Tasks

- [ ] read idea from slack https://ghost.slack.com/archives/C02G9E68C/p1516732377000504
- [x] remove access plugin
- [ ] replace pipeline
- [ ] change how we pass the incoming request params and body (use the options object)
- [ ] change how we return the model response

## Future
We would like to write an issue for transforming the context object into a class. And another issue about who is responsible to calling `toJSON` of a model - we have very heavy mixture of this concept.

**Comment by kirrg001** [comment]
Another thing we might want to reconsider is having the incoming body inside the `options` object. This is a little hard to take care of e.g. when passing options into the model layer. You always have to take to omit `options.data` e.g. [see](https://github.com/TryGhost/Ghost/pull/9380#pullrequestreview-87498091)

**Comment by Sjobom** [comment]
Me and some fellow CS students from KTH would like to take a look at replacing the pipeline if wanted!

Our thinking so far is that we would replace the pipeline with some code that only executes the given tasks sequentially. Each task would modify parameters by reference and the tasks would not need to return anything! 

@kirrg001 How does this sound like? 😸

**Comment by kirrg001** [comment]
@Sjobom We had a quick chat in slack. Are you still interested in this issue?

**Comment by kirrg001** [comment]
We had a quick chat in Slack.

The first short-term goals should be:
- rely on modification per reference
- each task doesn't have to return the options object
- pipeline utility always returns the options object with give modifications
- introduce `options.response` for model queries
- this allows us to return whatever we want from the API controlling unit (e.g. custom headers)

Long-term goal:
- transform the options object into a class
  - have control over original options, applied/modified options
  - have control over locked options
- transform context object into a class
- granular differentiation between API options and models options (e.g. `transacting` + `method` vs. `context` + `data`
- reconsider `options.data` - we often have to call `.omit(data)` before passing the options into the model layer - maybe this can be solved when we have a proper class e.g. `options.forModel`

**Comment by kirrg001** [comment]
@Sjobom I assume you won't continue with this task.

**Comment by kirrg001** [comment]
Closing this issue in favor of #9866.
