### ISSUE TITLE
Feature: Full Koenig Editor

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#9311]
As described in https://blog.ghost.org/1-0/#aneweditor, the current editor in Ghost 1.0 is a limited view of the full editor functionality we're in the process of building. We highly recommend reading that blog post to understand the Koenig editor project.

What we have currently, is purely the markdown card, which uses SimpleMDE (built on CodeMirror) to provide syntax highlighting and a nice experience writing markdown.

There are a few downsides to this setup - the biggest being that the spellcheck isn't great and is limited to English.

We're still working away on this feature. This issue serves mostly as a placeholder to track the overall progress. The first thing we will be doing is making the editor available behind a flag so that developing it becomes easier.

**The beta is now available in Labs!** - Please read the [beta announcement](https://forum.ghost.org/t/koenig-editor-beta-release/1284) for details on all the features. Test it out, and reply there on the forum if you run into any issues 😄

---

# Koenig development cycle

We are working in 6-week sprints with 2-week gaps between them, during each sprint we are aiming to improve Koenig's features and writing experience to a point where we can bump the version and increase it's availability to Ghost blog owners.

- [x] **[Alpha](https://github.com/TryGhost/Ghost/issues/9504)** - Available behind a dev+labs flag
- [x]  **[Beta](https://github.com/TryGhost/Ghost/issues/9505)** - Available behind a labs flag, not recommended for production (read the [beta announcement](https://forum.ghost.org/t/koenig-editor-beta-release/1284))
- [x] **[RC (release candidate)](https://github.com/TryGhost/Ghost/issues/9623)** - Available behind a labs flag
- [x] **[Final](https://github.com/TryGhost/Ghost/issues/9724)** - Default editor in Ghost 2.0

🏃 = "in progress"

## How to help test the Koenig Beta version <a name="help-test"></a>

First, please read the [beta announcement](https://forum.ghost.org/t/koenig-editor-beta-release/1284)

Ensure your you're on the most [recent release](https://github.com/TryGhost/Ghost/releases) (1.23.0 is the first version with Koenig on the labs screen) or your local development version is up to date ([`grunt master`](https://docs.ghost.org/docs/working-with-ghost#section-keeping-up-to-date) will help there).

Load the "Labs" screen in your blog admin and you will see a Koenig Editor checkbox to enable/disable the Koenig editor. Enable it and any post you start or edit will be using Koenig, disable it and you're back to the markdown editor.

:warning: Posts that have been edited with Koenig will only be editable with Koenig, even if you disable Koenig via labs. The only exception to this is posts that contain a single markdown card and no rich-text, they will open in the default Ghost 1.x editor when the labs flag is disabled.

**Comment by kevinansfield** [comment]
We have an inconsistency with card names, in the reboot I've named the cards with `koenig-` prefix so that the component names were more easily identifiable as editor related (`koenig-card-markdown`, `koenig-card-image`, etc). However the pre-1.0 alpha and our current markdown card do not have a `koenig-` prefix in the card names (`card-markdown`, `card-image`, etc).

I've "aliased" `card-markdown` to `koenig-card-markdown` for now but I think it could still do with some more thought around how we want to name cards.

I'm wondering if it will be easier to use basic card names for the built-in cards (`markdown`, `image`, etc) so that they can be more easily overridden by user-supplied custom cards later on. We could extend our `createComponentCard` utility to accept the card name as well as the component name so that we avoid the tight ties between card names and components that has led us into the current naming problems.

**Comment by kevinansfield** [comment]
Koenig is now available in beta behind a Labs flag in Ghost 1.23.0. Please read the [beta announcement](https://forum.ghost.org/t/koenig-editor-beta-release/1284) for full details 😄

**Comment by kevinansfield** [comment]
Koenig is now in the [final stretch](https://github.com/TryGhost/Ghost/issues/9724) before becoming Ghost 2.0's editor.

Please read the [beta announcement](https://forum.ghost.org/t/koenig-editor-beta-release/1284), try using it as your primary editor, and post all feedback on the [forum topic](https://forum.ghost.org/t/koenig-editor-beta-release/1284) so that we can catch any remaining issues before this thing ships! 🤗

**Note on browser support** - due to time constraints we've had to limit the browser support for the initial Koenig release:
- Microsoft Edge will not be supported
- Mobile editing will not be supported

Both of the above may work in limited capacities but will have known and unknown issues. Mobile editing will be more of a focus post-release, it requires further design work to deliver a good small-screen experience.

**Comment by kevinansfield** [comment]
Koenig is now out of beta and has replaced the old markdown editor in Ghost 2.0. Any bugs or features from this point will be tracked in separate issues.

Thanks for all the feedback during the beta period 😄

**Comment by zce** [comment]
@kevinansfield How to set code card language? 😄

**Comment by gustawdaniel** [comment]
@kevinansfield In prism plugins properties can be defined by data attribute in `pre` tag, but a language is defined by class `language-xxxx`

> https://prismjs.com/#languages-list

I now using `html` card no `pre`, but ealier In jekyll I used to applying syntax

```
```lang
code
code
code
\```  <-  without this "\" 
```

It would be nice if both data attributes and classes will be albe to define after typing "```" in koenig editor.
Also nice feature would be simpler integration with mathjs

Especially because of 

> https://help.ghost.org/article/89-mathjax

does not works and redirects to 

> https://docs.ghost.org/integrations/

**Comment by gustawdaniel** [comment]
Update. Syntax

```lang
code
code
code
\```  <-  without this "\" 

works with the prism in markdown card. But  if you are not inside of markdown card typing

\```

you create new not configurable card called code, but without proper highlight configuration, it is useless.
