### ISSUE TITLE
Dynamic Routing

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost#9601]
Refs: https://github.com/TryGhost/Ghost/issues/9528 (YAML Settings), https://github.com/TryGhost/Ghost/issues/9192 (Routing re-write), https://github.com/TryGhost/Ghost/pull/9550 (Url Service).

## The what and why of dynamic routing

Ghost's Routing has always been almost entirely static and hard-coded. The only config we've offered is the option to add dates to permalinks, but that setting is probably my least favourite part of Ghost 😂 

People close to the project will have heard a lot about a mysterious feature called "channels", which was an attempt to expose more configuration around lists of posts. This has been working behind the scenes, but we haven't been clear on how to expose the functionality: Apps? Config? UI?

Early this year we sat down and rethought routing from the ground up with a view to answering the following questions: How can we make it possible to solve all the common routing use cases? How do we expose functionality to our users?  How does this fit in with Apps? And where the fuck do Channels fit into all of this?

Top 3 common use cases we want to solve:

1. custom home pages
2. rendering a taxonomy at a non-standard URL, e.g. /tag/recipes/ -> /category/recipes/
3. customising post collections e.g. removing posts with a certain tag, or using a different URL

There are 3 main problems we have with trying to reach these use cases:

- How to make routes enumerable and configurable
- Ability to generate sitemaps and other features that need to know about URLs rather than routes
- Resource <-> URL 2 way binding - get resource from URL, get URL for resource

We think we have the answers, however the theory is never quite the same as the practice. This issue represents our current thinking at the time of writing and is very subject to change! 

## What's coming?

In https://github.com/TryGhost/Ghost/issues/9528 we added the ability to customise Ghost through YAML files that live in `content/settings`. The first file that will live here will be `routes.yaml`, and this will be the gateway to all things dynamic routing. This solve the configuration problem.

The solution to everything else is the introduction of a URL service and a huge rewrite of all the code that generates content for Ghost blogs 😅 

**Beta Goals**

In the first beta version, by editing `content/settings/routes.yml` it will be possible to:

- Define a custom route that renders a specific template
- Define a custom home page 
- Change the location of the standard collection of posts, e.g. so they all live at `/blog/*`.
- Change the URL for taxonomies e.g `/tag/:slug/` -> `/category/:slug/`
- Customise the main post collection (v1 has severe known limitations)
- Define new collections (v1 has severe known limitations)
 
Once the first beta goes out we will be looking for people to test their routing use-cases. At that point, we'll publish some documentation on how the default routes.yml file is structured and how to define custom routes and collections within the limitations. 

**Tracked tasks**

- [x] YAML Settings #9528 
- [x] Url Service rewrite #9550 
- [x] Dynamic sitemap 100% working (https://github.com/TryGhost/Ghost/pull/9580)
- [x] Rework url utility https://github.com/TryGhost/Ghost/pull/9593
- [x] Routing re-write https://github.com/TryGhost/Ghost/pull/9596
- [x] render 503 if url service is processing (https://github.com/TryGhost/Ghost/pull/9588)
- [x] Resources have full 2-way binding https://github.com/TryGhost/Ghost/pull/9596

**Overall Goals**

This issue will be closed when we achieve the following:

- [x] Ship first beta version of dynamic routing
- [x] First version of channels (https://github.com/TryGhost/Ghost/pull/9686)
  - [x] Resource path aliases with automatic redirects (Need a separate issue explaining this feature!)
- [x] Data key, order, limit, redirect
- [x] Disable rss (https://github.com/TryGhost/Ghost/pull/9693)
- [x] **Extracted**: disable sitemaps, disable pagination (https://github.com/TryGhost/Ghost/issues/10313)
- [x] **Extracted**: All hard-coded public routes (e.g. page) are configurable inc homepage (https://github.com/TryGhost/Ghost/issues/10312)
- [x] Add UI to upload+reload routes.yaml file (https://github.com/TryGhost/Ghost/issues/9744)

_Note: There are some extensions to the dynamic routing behaviour that are known but not covered by this issue, which include custom controllers and custom taxonomies_

💡 **Please direct all questions & discussion to the [forum](https://forum.ghost.org).** This issue will be used for collecting bugs & use cases once the beta goes out.

**Comment by fernandops26** [comment]
Will this feature be in ghost-free too?

**Comment by vikaspotluri123** [comment]
@fernandops26 Ghost self-hosted and Ghost (Pro) run [essentially] the same exact code; features like dynamic routing will be available in both Ghost (Pro) and Ghost self-hosted.

**Comment by pascalandy** [comment]
Those two points are killers:

- custom static pages
- **removing posts with a certain tag**, or using a different URL

This first point will open a whole new market for custom "landing page" manage within Ghost. Love it!

**Comment by kirrg001** [comment]
FYI: We will officially announce Dynamic Routing Beta in Ghost 2.0.

**Comment by kirrg001** [comment]
Dynamic Routing Beta was shipped in Ghost [1.24.0](https://github.com/TryGhost/Ghost/releases/tag/1.24.0). I am closing this issue for now. I extracted two sub features, which we aren't able to achieve yet.

Any further improvement or bug should be tracked separately 👻
