### ISSUE TITLE
Koenig: Final Ghost 2.0 Version

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost#9724]
This issue captures the tasks that we'll be working on for the fourth 6-week Koenig sprint. All work will take place on **master** and will be available in the weekly releases behind a labs flag for anyone wanting to help test. The plan is to replace Ghost's current editor with Koenig at the end of the cycle.

part of TryGhost/Ghost#9311 (Feature: Full Koenig editor)

### I want to help test! How do I get started?

See the [instructions here](https://github.com/tryghost/ghost/issues/9311#user-content-help-test).

---

🏃 in-progress
🚢 ready for next release (typically every Tuesday)

## Release blockers

- [ ] ✨ supported sources popup / help page for embed card
- [x] ✨ unsupported browser / mobile editing communication
    - basic implementation in https://github.com/TryGhost/Ghost-Admin/commit/b2a9e4cdd5fb4042d47489b1b0cb691bcb63f3cb

**Released:**
- [x] ✨ word count / reading time display
- [x] ✨ full text-editing keyboard shortcuts implementation
- [x] 🎨 <kbd>Cmd+Enter</kbd> should exit card edit mode as well as enter it
- [x] 🐛 Support schema-less URLs in embed cards
- [x] 🐛 Firefox <kbd>Up/Down</kbd> arrow keys jump to top/bottom of doc when hitting a section boundary
    - this is caused by `display: flex` on the `contenteditable` element and appears to be a Firefox bug
    - removing `display: flex` breaks larger image widths
- [x] 🐛 Slash-menu doesn't work after clicking "New story" whilst in the editor
- [x] 🐛 Clicking Embed cards from the /-menu throws errors
- [x] 🐛 Clicking the "Retry" link in the embed card error message doesn't return to URL input
- [x] 🐛 Clicking Markdown/HTML/embed cards from the /-menu doesn't create the card
- [x] 🐛 Firefox triple-click to select then typing doesn't replace content ([mobiledoc-kit issue](https://github.com/bustle/mobiledoc-kit/issues/592), [PR](https://github.com/bustle/mobiledoc-kit/pull/593))
- [x] 🐛 <kbd>Option + Backspace</kbd> delete only until the first letter with accent ([mobiledoc-kit issue](https://github.com/bustle/mobiledoc-kit/issues/628), [PR](https://github.com/bustle/mobiledoc-kit/pull/632))
- [x] 🐛 Safari scrolls to the bottom when interacting with the link toolbar
- [x] 🐛 Double-clicks on the MD card whilst it's selected can unexpectedly trigger toolbar buttons when transitioning to edit mode
- [x] 🐛 Clicking the (+) button when the cursor is not in the respective blank paragraph moves the cursor rather than opening the menu. Requires a second click to open
- [x] 🐛 Firefox <kbd>Up</kbd> requires two presses to move up from a divider card and gets stuck on image cards
- [x] 🐛 Safari doesn't display "wide" images correctly at all window sizes
- [x] 🐛 Dropping an image on the editor before a cursor has been placed throws an error
- [x] 🐛 Dropping an image on an image card creates two image cards
- [x] 🐛 Cutting a selection that includes a list item and a card loses the card when pasting ([mobiledoc-kit issue](https://github.com/bustle/mobiledoc-kit/issues/637), [PR](https://github.com/bustle/mobiledoc-kit/pull/638))

## Stretch goals

- [x] ✨ hide sidebar on editor screen
- [x] ✨ support `/image https://example.com/image.jpeg` slash menu shortcut
- [x] ✨ create an embed card when pasting a URL in a blank section if it matches a known provider
- [x] ✨ rich-text captions
- [x] ✨ 🚢 Unsplash image selection for image card
- [x] ✨ 🚢 general docs and help popup / link
- ✨ create an embed card based on opengraph data if there's no direct oembed provider
- ✨ warn if leaving whilst an upload is in progress
- 🐛 emoji's do not play nicely with the cursor. With 🤷🏻‍♂️ for example you need to press <kbd>Left</kbd> 6 times to move the cursor from one side to the other and <kbd>Backspace</kbd> will cycle through various forms of the emoji until it's finally deleted and doesn't always play nicely with the undo stack
    - Dropbox Paper converts all emoji's into an "atom" type element
    - Medium has similar struggles except it also doesn't render correctly
    - [mobiledoc-kit issue](https://github.com/bustle/mobiledoc-kit/issues/629)

**Comment by JohnONolan** [comment]
When pasting instagram URL - https://www.instagram.com/p/Bjo_mgTjOH-/?taken-by=johnonolan

(very broken)

![image](https://user-images.githubusercontent.com/120485/43796868-673f5142-9a7d-11e8-86d7-af1412aaa77c.png)

On refresh (partially broken)

![image](https://user-images.githubusercontent.com/120485/43796898-7cf07160-9a7d-11e8-958c-b0a845c5b79e.png)

**Comment by JohnONolan** [comment]
Not sure if Twitter is considered an oembed provider, but pasting https://twitter.com/vanschneider/status/1026867048624934917 doesn't do anything - on other editors it renders embedded tweet

**Comment by JohnONolan** [comment]
actually maybe the instagram embed is crashing it - none of them work

![image](https://user-images.githubusercontent.com/120485/43797141-5b6733de-9a7e-11e8-9002-280583e81419.png)

---

then when refreshing, and trying again, it does work - but no CSS

---

![image](https://user-images.githubusercontent.com/120485/43797214-904e87dc-9a7e-11e8-8b7f-120fbe6fb8d0.png)

---

then when refreshing again it renders

---

![image](https://user-images.githubusercontent.com/120485/43797252-b30f0c10-9a7e-11e8-8cce-a23b963eadff.png)

---

No errors in the console while the styles were broken or while oembeds werent unfurling

**Comment by kevinansfield** [comment]
2.0 has been cut, any outstanding Koenig bugs or features will be opened as separate issues.

The embed card loading bug referenced in the comments above has been opened https://github.com/TryGhost/Ghost/issues/9796
