### ISSUE TITLE
Image Size error optimisation

### ISSUE THREAD

**Issue by AileenCGN** [TryGhost/Ghost#9856]
## Issue Summary
The image size functionality is used in the code base for AMP requirements as well as meta data, such as JSON-LD, OG and Twitter. It determines the image dimensions (width and height).

Errors that happen during the process of fetching the image size are being written to the logs of a blog. Some of these errors can be prevented and could possible free up some log space.

It seems insignificant to not output the image size in our meta data, but Google requires image dimensions for AMP (see https://github.com/TryGhost/Ghost/issues/7558) and users will receive mails from Google if the structured data is not valid according to the [Data structure testing](https://search.google.com/structured-data/testing-tool/u/0/) tool 🙄.

## Cases to investigate and (potentially) fix
_Note_: Blogs with content pre 1.0 can have a URL as a post feature image. Most of the cases you need to investigate are related to image URLs. The easiest way to reproduce this with a 2.x blog is to change the URL for `feature_image` in the `post` table of the database. This way you can simulate the cases for image URLs.

### Case 1: Image URL starts with a whitespace
When an image URL starts with a whitespace, [the dependency](https://github.com/chriso/validator.js) we're using to validate a URL does not recognise the URL as a valid one. I think there could be multiple approaches to fix this. The probably easiest way is to strip out whitespaces before we pass the value to the validator. The validation happens [here](https://github.com/tryghost/ghost/blob/master/core/server/lib/request.js#L7).

### Case 2: Image URL is a video embed file
Some image URLs are actually video embeds (example: https://www.youtube.com/embed/uCLdi1FmHCI). These URLs should not be processed by our image size util. I can imagine that we use a regex check to skip the attempt of fetching the image size for URL that have a `https://www.youtube.com` or `vimeo` pattern (others that I can't think of now as well 😉). Most of the checks before fetching the dimensions happen [here](https://github.com/tryghost/ghost/blob/master/core/server/lib/image/image-size.js#L80).

### Case 3: Fetching the image times out
The current timeout in Ghost is set to 5000ms, which is already too high and should probably be more like 2-3s (this should be tested and invested properly). Nevertheless this is the most logged error. That's why we should remove the logging of it.

### Case 4: No permission (403) to read image URL
Some image URLs that are used might not be accessible by the public and the server responses with a 403. We should definitely handle those cases and prevent any further actions, such as logging and trying to fetch the image size.

---

## Todos:
- [ ] investigate where further improvements can be made and post them in this issue
- [ ] remove logging of time out errors and decrease time out
- [ ] prevent video URLs from being processed
- [ ] investigate and fix the issue with whitespaces in the URL either in our codebase or in the dependency directly
- [ ] handle the 403 errors and don't log them

**Comment by ErisDS** [comment]
Closing due to inactivity
